'use client';
import {useEffect,useRef,useState} from 'react';
import {ContentJourney} from '../../components/ContentJourney';

const writerName:any={control:'写作路径一',human_writing:'写作路径二',ultimate_fusion:'写作路径三'};
const labelName:any={worth_learning:'值得长期参考',one_off:'单篇修改',fact_correction:'事实纠正'};
const blankBrief=()=>({starting_idea:'',problem:'',user_judgment:'',experiences:[],examples:[],counterarguments:[],boundaries:[],angle:'',desired_reader_reaction:'',useful_original_quotes:[],evidence_needed:[],conversation_summary:''});
const lines=(value:string)=>value.split(/\n+/).map(x=>x.trim()).filter(Boolean);
const lineValue=(value:any)=>Array.isArray(value)?value.join('\n'):'';

function BriefEditor({brief,onChange,disabled}:{brief:any;onChange:(next:any)=>void;disabled?:boolean}){
  const field=(key:string,label:string,help?:string)=><label className="creator-brief-field"><span>{label}</span>{help&&<small>{help}</small>}<textarea disabled={disabled} value={brief[key]||''} onChange={e=>onChange({...brief,[key]:e.target.value})}/></label>;
  const listField=(key:string,label:string,help?:string)=><label className="creator-brief-field"><span>{label}</span>{help&&<small>{help}</small>}<textarea disabled={disabled} value={lineValue(brief[key])} onChange={e=>onChange({...brief,[key]:lines(e.target.value)})}/></label>;
  return <div className="creator-brief-grid">
    {field('problem','这篇到底要讨论什么？')}
    {field('user_judgment','你的判断是什么？')}
    {listField('experiences','真实经历','一行一件；可以很小。')}
    {listField('examples','具体例子','一行一个场景、人物或细节。')}
    {field('angle','内容从哪里切进去？')}
    {field('desired_reader_reaction','希望读者最后带走什么？')}
    <details className="creator-brief-details"><summary>补充边界、原话与需要核实的事</summary>{listField('counterarguments','反例 / 不同意见')}{listField('boundaries','边界 / 不要写成什么')}{listField('useful_original_quotes','想保留的原话')}{listField('evidence_needed','仍需核实')}</details>
  </div>;
}

export default function EditorClient(){
  const generateAbort=useRef<AbortController|null>(null);
  const[item,setItem]=useState<any>(null),[viewpoint,setViewpoint]=useState(''),[finalText,setFinal]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[nextUrl,setNextUrl]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
  const[noId,setNoId]=useState(false),[unfinished,setUnfinished]=useState<any[]>([]),[calibrationBusy,setCalibrationBusy]=useState(false),[chatInput,setChatInput]=useState(''),[briefDraft,setBriefDraft]=useState<any>(blankBrief()),[directSaveError,setDirectSaveError]=useState('');
  const applyItem=(x:any)=>{setItem(x);if(x){setViewpoint(x.user_raw_input||'');setBriefDraft(x.calibration?.brief||blankBrief());const chosen=(x.versions||[]).filter((v:any)=>v.version_type==='candidate'&&v.candidate_set_id).at(-1);const finals=(x.versions||[]).filter((v:any)=>v.version_type==='final');const latestFinal=finals.at(-1);const useFinal=chosen&&latestFinal&&new Date(latestFinal.created_at)>=new Date(chosen.created_at);setFinal(useFinal?latestFinal.body:(chosen?.body||''))}};
  const load=async()=>{setLoading(true);setLoadError('');try{const id=new URLSearchParams(location.search).get('id');if(!id){setNoId(true);const r=await fetch('/api/content?list=unfinished',{cache:'no-store'});if(!r.ok)throw Error('读取未完成内容失败');setUnfinished((await r.json()).items||[]);setItem(null);return}setNoId(false);const r=await fetch(`/api/content?id=${encodeURIComponent(id)}`,{cache:'no-store'});if(!r.ok)throw Error('读取内容失败');applyItem((await r.json()).item)}catch(e:any){setLoadError(e?.message||'读取内容失败')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const updateCalibration=(calibration:any,syncBrief=true)=>{if(!calibration)return;setItem((old:any)=>old?{...old,calibration,calibrationEligible:true}:old);if(syncBrief)setBriefDraft(calibration.brief||blankBrief())};
  const calibrationRequest=async(action:string,extra:any={})=>{if(!item)return null;try{const r=await fetch('/api/content/calibration',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,action,...extra})});const x=await r.json();if(x.calibration)updateCalibration(x.calibration,action!=='save_brief');if(!x.ok)setMsg(x.error||'这一步暂时没有完成。');return x}catch{setMsg('网络连接暂时中断，输入还留在这里。请重试。');return null}};
  const calibration=item?.calibration,steps=item?.blindSet,generating=steps?.status==='generating',awaiting=steps?.status==='awaiting_choice',selected=steps?.status==='winner_selected',rejected=steps?.status==='rejected_all';
  const chosen=selected?(steps.candidates||[]).find((c:any)=>c.id===steps.winner_variant_id):null;
  const hasFinal=Boolean(item?.final_text)||(item?.versions||[]).some((v:any)=>v.version_type==='final'&&chosen&&new Date(v.created_at)>=new Date((item?.versions||[]).filter((x:any)=>x.version_type==='candidate'&&x.candidate_set_id).at(-1)?.created_at||0));
  const hasWorkflow=Boolean(steps)||hasFinal||(item&&item.content_state!=='awaiting_viewpoint');
  const canCalibrate=Boolean(item&&(item.calibrationEligible||calibration)&&!hasWorkflow);
  const hasChosenMode=calibration?.mode==='chat'||calibration?.mode==='direct';
  const chatMode=canCalibrate&&calibration?.mode==='chat';
  const chatInherited=calibration?.mode==='chat'&&calibration?.status==='confirmed';
  const directMode=Boolean(item)&&((!canCalibrate&&calibration?.mode!=='chat')||calibration?.mode==='direct');

  useEffect(()=>{if(!item||!canCalibrate||calibration?.mode!=='direct')return;const timer=window.setTimeout(async()=>{const x=await calibrationRequest('direct_draft',{directText:viewpoint});if(x?.ok)setDirectSaveError('');else if(x)setDirectSaveError('没有保存成功，会在你下次修改时重试。')},700);return()=>window.clearTimeout(timer)},[viewpoint,item?.id,calibration?.mode,canCalibrate]);
  useEffect(()=>{if(!item||!chatMode||calibration?.status!=='brief_ready')return;const timer=window.setTimeout(async()=>{const x=await calibrationRequest('save_brief',{brief:briefDraft});if(x?.ok)setMsg('')},800);return()=>window.clearTimeout(timer)},[briefDraft,item?.id,chatMode,calibration?.status]);

  const generate=async(inputText?:string)=>{if(!item)return;setBusy(true);setMsg('正在准备第 1/3 篇草稿…');const request:any={contentId:item.id},text=(inputText===undefined?viewpoint:inputText).trim();if(text)request.viewpoint=text;let completed=steps?.candidates?.length||0;try{for(let i=0;i<3;i++){const controller=new AbortController();generateAbort.current=controller;const timer=window.setTimeout(()=>controller.abort(),90000);try{const r=await fetch('/api/content/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request),signal:controller.signal});const x=await r.json();if(!x.ok){setMsg(x.needsKey?'写作服务还没有配置好。':'生成中断：'+x.error+'。已经完成的草稿会保留，可以稍后继续。');break}completed=x.generatedCount??completed;if(x.complete){setMsg('三篇草稿已经准备好。下一步：选一篇继续修改。');break}setMsg(`已完成 ${completed}/3 篇，正在继续准备下一篇。`)}finally{window.clearTimeout(timer)}}}catch(e:any){setMsg(e?.name==='AbortError'?`生成已停止。已完成的 ${completed} 篇不会丢失，可以点击重试继续。`:`生成中断：${e?.message||'网络异常'}。已完成的 ${completed} 篇不会丢失，可以稍后重试。`)}finally{generateAbort.current=null;setBusy(false);await load()}};
  const cancelGenerate=()=>{generateAbort.current?.abort()};
  const startChat=async()=>{setCalibrationBusy(true);setMsg('');await calibrationRequest('start');setCalibrationBusy(false)};
  const useDirect=async()=>{setCalibrationBusy(true);const x=await calibrationRequest('direct_draft',{directText:viewpoint});if(x?.ok)setMsg('可以直接写下你的观点；内容会自动保存。');setCalibrationBusy(false)};
  const sendChat=async()=>{const text=chatInput.trim();if(!text)return;setCalibrationBusy(true);const x=await calibrationRequest('reply',{text});if(x)setChatInput('');setCalibrationBusy(false)};
  const retryChat=async()=>{setCalibrationBusy(true);await calibrationRequest('retry');setCalibrationBusy(false)};
  const continueChat=async()=>{setCalibrationBusy(true);await calibrationRequest('continue');setCalibrationBusy(false)};
  const confirmBrief=async()=>{setCalibrationBusy(true);const x=await calibrationRequest('confirm_brief',{brief:briefDraft});if(x?.ok){setViewpoint('');setMsg('写作理解已确认，正在使用已保存的对话原话、经历和内容 Brief 准备草稿…');setCalibrationBusy(false);await generate('');return}setCalibrationBusy(false)};
  const choose=async(choice:string)=>{if(!item)return;setBusy(true);const r=await fetch('/api/content/choose',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,setId:steps.id,choice})});const x=await r.json();if(x.ok){if(choice==='NONE')setMsg('已记录：三篇都不合适。可以重新准备一组草稿。');else{const picked=x.set.candidates.find((c:any)=>c.id===x.set.winner_variant_id);setFinal(picked?.body||'');setMsg(`已选中${choice}，下一步：确认并修改最终稿。`)}}else setMsg('选择失败：'+x.error);setBusy(false);await load()};
  const save=async()=>{if(!item)return;setBusy(true);const r=await fetch('/api/content/final',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,finalText})});const x=await r.json();setMsg(x.ok?'定稿已保存。下一步：准备发布。':'保存失败：'+x.error);if(x.ok)setNextUrl(x.nextUrl||`/publish?id=${item.id}`);setBusy(false);await load()};
  const label=async(value:string)=>{if(!item)return;const r=await fetch('/api/content/label',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,label:value})});const x=await r.json();setMsg(x.ok?`已标记：${labelName[value]||value}`:'标记失败');await load()};

  if(loading)return <div className="card">正在读取这条内容…</div>;
  if(loadError)return <div className="card">{loadError}<div style={{marginTop:10,display:'flex',gap:8}}><button onClick={load}>重试读取</button><a className="button-link secondary" href="/topics">返回选题 →</a></div></div>;
  if(noId)return <section className="card editor-empty-state"><div className="eyebrow">写作从一条新内容开始</div><h1>先开始一条新内容</h1><p className="muted">这里不会替你打开任何旧草稿、已定稿或已完成内容。可以直接写下自己的话题，也可以从推荐选题开始，或明确选择你要继续的未完成任务。</p><div className="creator-actions"><a className="button-link" href="/topics#manual-topic">自己开始写 →</a><a className="button-link secondary" href="/topics">浏览推荐选题 →</a></div>{unfinished.length>0&&<div className="unfinished-list"><h2>继续未完成内容</h2>{unfinished.map((entry:any)=><a className="unfinished-item" key={entry.id} href={`/editor?id=${encodeURIComponent(entry.id)}`}><span><strong>{entry.title}</strong><small>{entry.stateLabel}</small></span><span>继续 →</span></a>)}</div>}</section>;
  if(!item)return <div className="card">没有找到这条内容。</div>;
  const current=hasFinal?'visual':selected?'final':awaiting?'choose':generating?'draft':'viewpoint';
  return <><ContentJourney current={current}/><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">{item.title}</span><span className="pill">{item.stateLabel||'写作中'}</span></div>{msg&&<p className="muted" style={{whiteSpace:'pre-wrap'}}>{msg}</p>}{nextUrl&&<a className="button-link" href={nextUrl}>准备发布 →</a>}</div>
    {!hasWorkflow&&!hasChosenMode&&<section className="card creator-choice" id="viewpoint"><div className="eyebrow">写前对齐</div><h2>先把真正想说的事理清</h2><p className="muted">你可以和 Sinote 安静聊几句，也可以直接开始写。两条路都会进入同一套三稿流程。</p><div className="creator-choice-grid"><button className="creator-choice-card" disabled={calibrationBusy} onClick={startChat}><span>跟 Sinote 聊聊</span><small>从一个模糊念头聊到可写的判断、经历和入口。</small></button><button className="creator-choice-card secondary" disabled={calibrationBusy} onClick={useDirect}><span>我已经想清楚了</span><small>直接写下观点和素材，马上生成三篇草稿。</small></button></div>{calibrationBusy&&<p className="muted" style={{marginBottom:0}}>Sinote 正在先读懂这条内容…</p>}</section>}
    {chatMode&&calibration?.status!=='confirmed'&&<section className="card" style={{marginBottom:16}}><div className="eyebrow">聊清楚再写</div><h2>{calibration.status==='brief_ready'?'确认 Sinote 的理解':'把想法聊具体'}</h2>{(calibration.messages||[]).map((m:any,i:number)=><div className={`creator-chat-message ${m.role}`} key={i}><strong>{m.role==='assistant'?'Sinote':'你'}</strong><p>{m.content}</p></div>)}{calibration.status==='brief_ready'?<><BriefEditor brief={briefDraft} onChange={setBriefDraft} disabled={calibrationBusy}/><div className="creator-actions"><button disabled={calibrationBusy} onClick={confirmBrief}>确认理解并生成草稿</button><button className="secondary" disabled={calibrationBusy} onClick={continueChat}>继续聊两句</button></div></>:<><textarea value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="想到什么就说什么，不需要组织成文章。"/><div className="creator-actions"><button disabled={calibrationBusy||!chatInput.trim()} onClick={sendChat}>发送</button>{calibration.status==='failed'&&<button className="secondary" disabled={calibrationBusy} onClick={retryChat}>重试</button>}</div></>}</section>}
    {chatInherited&&<section className="card" style={{marginBottom:16}}><div className="eyebrow">写前对齐已完成</div><h2>Sinote 会沿用这次对话继续写</h2><p className="muted">你的原话、经历、边界和确认过的 Brief 已保存，不需要重新填写。</p></section>}
    {directMode&&<section className="card" id="viewpoint" style={{marginBottom:16}}><div className="eyebrow">观点 / 素材</div><h2>把你已经想清楚的事写下来</h2><p className="muted">判断、例子、口述原话都可以。新内容会自动保存；已有三稿与定稿会完全沿用原来的流程。</p><textarea value={viewpoint} onChange={e=>setViewpoint(e.target.value)} placeholder="例如：我真正想让读者听懂什么？有哪些亲身经历或课堂例子？"/>{directSaveError&&<p className="muted">{directSaveError}</p>}<button onClick={()=>generate()} disabled={busy||!viewpoint.trim()||awaiting} style={{marginTop:10}}>{busy?'生成中…':generating?'继续准备草稿':steps?'再准备一组草稿':'生成三篇草稿'}</button>{busy&&<button className="secondary" onClick={cancelGenerate} style={{marginLeft:8}}>取消生成</button>}{generating&&<span className="muted" style={{marginLeft:10}}>三篇齐全前不会展示正文。</span>}{awaiting&&<span className="muted" style={{marginLeft:10}}>先完成选稿，再开始修改。</span>}</section>}
    {awaiting&&<section className="card" id="drafts"><h2>下一步：选一篇继续修改</h2><p className="muted">先只判断哪一篇最接近你的表达，不需要现在改字。</p><div className="blind-grid">{steps.candidates.map((c:any)=><article className="blind-card" key={c.id}><div className="eyebrow">草稿 {c.label}</div><div className="blind-body">{c.body}</div><button onClick={()=>choose(c.label)} disabled={busy}>选这篇</button></article>)}</div><button className="secondary" onClick={()=>choose('NONE')} disabled={busy} style={{marginTop:12}}>三篇都不合适</button></section>}
    {rejected&&<section className="card"><h2>这组三稿都不合适</h2><p className="muted">已经保留当前结果。可以补充观点后重新准备一组。</p><button onClick={()=>generate()} disabled={busy}>重新准备三篇草稿</button>{busy&&<button className="secondary" onClick={cancelGenerate} style={{marginLeft:8}}>取消生成</button>}</section>}
    {selected&&chosen&&<><section className="card" id="drafts" style={{marginBottom:16}}><h2>选中的草稿</h2><div className="meta">{steps.candidates.map((c:any)=><span className="pill" key={c.label}>草稿 {c.label} · {writerName[c.writerKey]||'写作路径'}{c.id===steps.winner_variant_id?' · 已选':''}</span>)}</div></section><div className="split" id="final"><div className="card"><h2>选中的草稿 · {chosen.label}</h2><textarea value={chosen.body} readOnly/></div><div className="card"><h2>最终正文 / 定稿</h2><textarea value={finalText} onChange={e=>setFinal(e.target.value)}/><div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button onClick={save} disabled={busy||!finalText.trim()}>确认最终稿</button>{hasFinal&&<><button className="secondary" onClick={()=>label('worth_learning')}>值得长期参考</button><button className="secondary" onClick={()=>label('one_off')}>单篇修改</button><button className="secondary" onClick={()=>label('fact_correction')}>事实纠正</button></>}</div></div></div></>}
    {(item.observations||[]).length>0&&selected&&<div className="card" style={{marginTop:16}}><h2>修改对照</h2>{item.observations.slice(0,12).map((o:any)=><p key={o.id}><span className="diff-old">{o.before_text}</span> → <span className="diff-new">{o.after_text}</span> · {o.explanation}</p>)}</div>}
  </>
}
