'use client';
import {useEffect,useState} from 'react';
import {ContentJourney} from '../../components/ContentJourney';

const writerName:any={control:'写作路径一',human_writing:'写作路径二',ultimate_fusion:'写作路径三'};
const labelName:any={worth_learning:'值得长期参考',one_off:'单篇修改',fact_correction:'事实纠正'};
const blankBrief=()=>({starting_idea:'',problem:'',user_judgment:'',experiences:[],examples:[],counterarguments:[],boundaries:[],angle:'',desired_reader_reaction:'',useful_original_quotes:[],evidence_needed:[],conversation_summary:''});
const lines=(value:string)=>value.split(/\n+/).map(x=>x.trim()).filter(Boolean);
const lineValue=(value:any)=>Array.isArray(value)?value.join('\n'):'';

function BriefEditor({brief,onChange,disabled}:{brief:any;onChange:(next:any)=>void;disabled?:boolean}){
  const field=(key:string,label:string,help?:string)=><label className="creator-brief-field"><span>{label}</span>{help&&<small>{help}</small>}<textarea disabled={disabled} value={brief[key]||''} onChange={e=>onChange({...brief,[key]:e.target.value})}/></label>;
  const listField=(key:string,label:string,help?:string)=><label className="creator-brief-field"><span>{label}</span>{help&&<small>{help}</small>}<textarea disabled={disabled} value={lineValue(brief[key])} onChange={e=>onChange({...brief,[key]:lines(e.target.value)})}/></label>;
  return <div className="creator-brief-grid">
    {field('problem','这篇到底要讨论什么？')}
    {field('user_judgment','你的判断是什么？')}
    {listField('experiences','真实经历','一行一件；可以很小。')}
    {listField('examples','具体例子','一行一个场景、人物或细节。')}
    {field('angle','内容从哪里切进去？')}
    {field('desired_reader_reaction','希望读者最后带走什么？')}
    <details className="creator-brief-details"><summary>补充边界、原话与需要核实的事</summary>{listField('counterarguments','反例 / 不同意见')}{listField('boundaries','边界 / 不要写成什么')}{listField('useful_original_quotes','想保留的原话')}{listField('evidence_needed','仍需核实')}</details>
  </div>;
}

export default function EditorClient(){
  const[item,setItem]=useState<any>(null),[viewpoint,setViewpoint]=useState(''),[finalText,setFinal]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[nextUrl,setNextUrl]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
  const[noId,setNoId]=useState(false),[unfinished,setUnfinished]=useState<any[]>([]),[calibrationBusy,setCalibrationBusy]=useState(false),[chatInput,setChatInput]=useState(''),[briefDraft,setBriefDraft]=useState<any>(blankBrief()),[directSaveError,setDirectSaveError]=useState('');
  const applyItem=(x:any)=>{setItem(x);if(x){setViewpoint(x.user_raw_input||'');setBriefDraft(x.calibration?.brief||blankBrief());const chosen=(x.versions||[]).filter((v:any)=>v.version_type==='candidate'&&v.candidate_set_id).at(-1);const finals=(x.versions||[]).filter((v:any)=>v.version_type==='final');const latestFinal=finals.at(-1);const useFinal=chosen&&latestFinal&&new Date(latestFinal.created_at)>=new Date(chosen.created_at);setFinal(useFinal?latestFinal.body:(chosen?.body||''))}};
  const load=async()=>{setLoading(true);setLoadError('');try{const id=new URLSearchParams(location.search).get('id');if(!id){setNoId(true);const r=await fetch('/api/content?list=unfinished',{cache:'no-store'});if(!r.ok)throw Error('读取未完成内容失败');setUnfinished((await r.json()).items||[]);setItem(null);return}setNoId(false);const r=await fetch(`/api/content?id=${encodeURIComponent(id)}`,{cache:'no-store'});if(!r.ok)throw Error('读取内容失败');applyItem((await r.json()).item)}catch(e:any){setLoadError(e?.message||'读取内容失败')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const updateCalibration=(calibration:any,syncBrief=true)=>{if(!calibration)return;setItem((old:any)=>old?{...old,calibration,calibrationEligible:true}:old);if(syncBrief)setBriefDraft(calibration.brief||blankBrief())};
  const calibrationRequest=async(action:string,extra:any={})=>{if(!item)return null;try{const r=await fetch('/api/content/calibration',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,action,...extra})});const x=await r.json();if(x.calibration)updateCalibration(x.calibration,action!=='save_brief');if(!x.ok)setMsg(x.error||'这一步暂时没有完成。');return x}catch{setMsg('网络连接暂时中断，输入还留在这里。请重试。');return null}};
  const calibration=item?.calibration,steps=item?.blindSet,generating=steps?.status==='generating',awaiting=steps?.status==='awaiting_choice',selected=steps?.status==='winner_selected',rejected=steps?.status==='rejected_all';
  const chosen=selected?(steps.candidates||[]).find((c:any)=>c.id===steps.winner_variant_id):null;
  const hasFinal=Boolean(item?.final_text)||(item?.versions||[]).some((v:any)=>v.version_type==='final'&&chosen&&new Date(v.created_at)>=new Date((item?.versions||[]).filter((x:any)=>x.version_type==='candidate'&&x.candidate_set_id).at(-1)?.created_at||0));
  const hasWorkflow=Boolean(steps)||hasFinal||(item&&item.content_state!=='awaiting_viewpoint');
  const canCalibrate=Boolean(item&&(item.calibrationEligible||calibration)&&!hasWorkflow);
  const hasChosenMode=calibration?.mode==='chat'||calibration?.mode==='direct';
  const chatMode=canCalibrate&&calibration?.mode==='chat';
  // A confirmed chat already supplies the canonical writer context. Do not show
  // its old textarea again after refresh or while drafts are being prepared.
  const chatInherited=calibration?.mode==='chat'&&calibration?.status==='confirmed';
  const directMode=Boolean(item)&&((!canCalibrate&&calibration?.mode!=='chat')||calibration?.mode==='direct');

  useEffect(()=>{if(!item||!canCalibrate||calibration?.mode!=='direct')return;const timer=window.setTimeout(async()=>{const x=await calibrationRequest('direct_draft',{directText:viewpoint});if(x?.ok)setDirectSaveError('');else if(x)setDirectSaveError('没有保存成功，会在你下次修改时重试。')},700);return()=>window.clearTimeout(timer)},[viewpoint,item?.id,calibration?.mode,canCalibrate]);
  useEffect(()=>{if(!item||!chatMode||calibration?.status!=='brief_ready')return;const timer=window.setTimeout(async()=>{const x=await calibrationRequest('save_brief',{brief:briefDraft});if(x?.ok)setMsg('')},800);return()=>window.clearTimeout(timer)},[briefDraft,item?.id,chatMode,calibration?.status]);

  const generate=async(inputText?:string)=>{if(!item)return;setBusy(true);setMsg('正在准备第 1/3 篇草稿…');const request:any={contentId:item.id},text=(inputText===undefined?viewpoint:inputText).trim();if(text)request.viewpoint=text;for(let i=0;i<3;i++){const r=await fetch('/api/content/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});const x=await r.json();if(!x.ok){setMsg(x.needsKey?'写作服务还没有配置好。':'生成中断：'+x.error+'。已经完成的草稿会保留，可以稍后继续。');break}if(x.complete){setMsg('三篇草稿已经准备好。先只看哪一篇最接近你愿意继续修改的版本。');break}setMsg(`已完成 ${x.generatedCount}/3 篇，正在继续准备下一篇。`)}setBusy(false);await load()};
  const startChat=async()=>{setCalibrationBusy(true);setMsg('');await calibrationRequest('start');setCalibrationBusy(false)};
  const useDirect=async()=>{setCalibrationBusy(true);const x=await calibrationRequest('direct_draft',{directText:viewpoint});if(x?.ok)setMsg('可以直接写下你的观点；内容会自动保存。');setCalibrationBusy(false)};
  const sendChat=async()=>{const text=chatInput.trim();if(!text)return;setCalibrationBusy(true);const x=await calibrationRequest('reply',{text});if(x)setChatInput('');setCalibrationBusy(false)};
  const retryChat=async()=>{setCalibrationBusy(true);await calibrationRequest('retry');setCalibrationBusy(false)};
  const continueChat=async()=>{setCalibrationBusy(true);await calibrationRequest('continue');setCalibrationBusy(false)};
  const confirmBrief=async()=>{setCalibrationBusy(true);const x=await calibrationRequest('confirm_brief',{brief:briefDraft});if(x?.ok){setViewpoint('');setMsg('写作理解已确认，三位写作者正在使用已保存的对话原话、经历和 Brief 准备草稿…');setCalibrationBusy(false);await generate('');return}setCalibrationBusy(false)};
  const choose=async(choice:string)=>{if(!item)return;setBusy(true);const r=await fetch('/api/content/choose',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,setId:steps.id,choice})});const x=await r.json();if(x.ok){if(choice==='NONE')setMsg('已记录：三篇都不合适。可以重新准备一组草稿。');else{const picked=x.set.candidates.find((c:any)=>c.id===x.set.winner_variant_id);setFinal(picked?.body||'');setMsg(`已选中${choice}，接下来只修改这篇。`)}}else setMsg('选择失败：'+x.error);setBusy(false);await load()};
  const save=async()=>{if(!item)return;setBusy(true);const r=await fetch('/api/content/final',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,finalText})});const x=await r.json();setMsg(x.ok?`定稿已保存。共记录 ${x.observations?.length||0} 处修改，下一步做视觉。`:'保存失败：'+x.error);if(x.ok)setNextUrl(x.nextUrl||`/publish?id=${item.id}`);setBusy(false);await load()};
  const label=async(value:string)=>{if(!item)return;const r=await fetch('/api/content/label',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,label:value})});const x=await r.json();setMsg(x.ok?`已标记：${labelName[value]||value}`:'标记失败');await load()};

  if(loading)return <div className="card">正在读取这条内容…</div>;
  if(loadError)return <div className="card">{loadError}<div style={{marginTop:10,display:'flex',gap:8}}><button onClick={load}>重试读取</button><a className="button-link secondary" href="/topics">返回选题 →</a></div></div>;
  if(noId)return <section className="card editor-empty-state"><div className="eyebrow">写作从一条新内容开始</div><h1>先开始一条新内容</h1><p className="muted">这里不会替你打开任何旧草稿、已定稿或已完成内容。可以直接写下自己的话题，也可以从推荐选题开始，或明确选择你要继续的未完成任务。</p><div className="creator-actions"><a className="button-link" href="/topics#manual-topic">自己开始写 →</a><a className="button-link secondary" href="/topics">浏览推荐选题 →</a></div>{unfinished.length>0&&<div className="unfinished-list"><h2>继续未完成内容</h2>{unfinished.map((entry:any)=><a className="unfinished-item" key={entry.id} href={`/editor?id=${encodeURIComponent(entry.id)}`}><span><strong>{entry.title}</strong><small>{entry.stateLabel}</small></span><span aria-hidden="true">→</span></a>)}</div>}</section>;
  if(!item)return <div className="card">还没有找到这条内容。请返回「选题」重新开始。<div style={{marginTop:10}}><a className="button-link" href="/topics">返回选题 →</a></div></div>;
  const current=hasFinal?'visual':selected?'final':awaiting?'choose':generating?'draft':'viewpoint';
  const done=current==='visual'?['viewpoint','draft','choose','final']:current==='final'?['viewpoint','draft','choose']:current==='choose'?['viewpoint','draft']:current==='draft'?['viewpoint']:[];
  return <><ContentJourney contentId={item.id} current={current} doneSteps={done}/>
    <div className="card" style={{marginBottom:16}}><div className="eyebrow">当前内容</div><h1 style={{fontSize:28,marginTop:8}}>{item.topic_title}</h1><p className="muted" style={{marginBottom:0}}>这条内容会沿着上面的六步完成；刷新页面后仍会回到同一个内容任务。</p></div>
    {chatInherited&&<section className="card creator-inherited" aria-live="polite"><div className="eyebrow">已继承给写作者</div><h2>不需要再写一遍话题和素材</h2><p className="muted">三位写作者会从服务器读取并使用：你的对话原话、真实经历与例子、你确认的判断、内容入口，以及确认后的 Writing Brief。</p>{generating&&<div className="creator-actions"><button onClick={()=>generate('')} disabled={busy}>{busy?'正在准备草稿…':'继续准备草稿'}</button></div>}</section>}
    {!hasWorkflow&&!hasChosenMode&&<section className="card creator-choice" id="viewpoint"><div className="eyebrow">写前对齐</div><h2>先把真正想说的事理清</h2><p className="muted">你可以和 Sinote 安静聊几句，也可以直接开始写。两条路都会进入同一套三稿流程。</p><div className="creator-choice-grid"><button className="creator-choice-card" disabled={calibrationBusy} onClick={startChat}><span>跟 Sinote 聊聊</span><small>从一个模糊念头聊到可写的判断、经历和入口。</small></button><button className="creator-choice-card secondary" disabled={calibrationBusy} onClick={useDirect}><span>我已经想清楚了</span><small>直接写下观点和素材，马上生成三篇草稿。</small></button></div>{calibrationBusy&&<p className="muted" style={{marginBottom:0}}>Sinote 正在先读懂这条内容…</p>}</section>}
    {chatMode&&!chatInherited&&<section className="card creator-chat" id="viewpoint"><div className="eyebrow">写前对话</div><h2>{calibration?.status==='brief_ready'?'这是目前的写作理解':'先把你真正想讲的事聊清楚'}</h2><p className="muted">Sinote 每次只追问一个最值得说清的地方；你的原话、经历和例子都会随这条内容保存。</p><div className="creator-progress" aria-label="写作理解进度">{[['problem','问题'],['experiences','经历'],['user_judgment','判断'],['angle','入口']].map(([key,label])=><span key={key} className={Array.isArray(briefDraft[key])?briefDraft[key].length?'is-ready':'':briefDraft[key]?'is-ready':''}>{label}</span>)}</div><div className="creator-messages">{(calibration?.messages||[]).map((message:any)=><div className={`creator-message ${message.role==='user'?'is-user':'is-assistant'}`} key={message.id}><small>{message.role==='user'?'你':'Sinote'}</small><p>{message.body}</p></div>)}</div>{calibration?.last_error&&<div className="creator-error"><p>{calibration.last_error}</p><button className="secondary" disabled={calibrationBusy} onClick={retryChat}>重试刚才这一步</button></div>}{calibration?.status==='brief_ready'?<div className="creator-brief"><h3>Writing Brief</h3><p className="muted">可直接改；修改会自动保存。确认后，三位写作者都会收到这份 Brief 和你的原话。</p><BriefEditor brief={briefDraft} onChange={setBriefDraft} disabled={calibrationBusy}/><div className="creator-actions"><button className="secondary" disabled={calibrationBusy} onClick={continueChat}>继续聊聊</button><button disabled={calibrationBusy} onClick={confirmBrief}>{calibrationBusy?'正在确认…':'这个意思对，开始写'}</button></div></div>:<div className="creator-composer"><textarea value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="想到什么就说什么：一段经历、一个不舒服的瞬间、一个判断都可以。"/><div className="creator-actions"><button disabled={calibrationBusy||!chatInput.trim()} onClick={sendChat}>{calibrationBusy?'Sinote 正在理解…':'把这段告诉 Sinote'}</button><button className="secondary" disabled={calibrationBusy} onClick={useDirect}>我想直接写</button></div></div>}</section>}
    {directMode&&<section className="card" id="viewpoint" style={{marginBottom:16}}><div className="eyebrow">观点 / 素材</div><h2>把你已经想清楚的事写下来</h2><p className="muted">判断、例子、口述原话都可以。新内容会自动保存；已有三稿与定稿会完全沿用原来的流程。</p><textarea value={viewpoint} onChange={e=>setViewpoint(e.target.value)} placeholder="例如：我真正想让读者听懂什么？有哪些亲身经历或课堂例子？"/>{directSaveError&&<p className="muted">{directSaveError}</p>}<button onClick={()=>generate()} disabled={busy||!viewpoint.trim()||awaiting} style={{marginTop:10}}>{busy?'处理中…':generating?'继续准备草稿':steps?'再准备一组草稿':'生成三篇草稿'}</button>{generating&&<span className="muted" style={{marginLeft:10}}>三篇齐全前不会展示正文。</span>}{awaiting&&<span className="muted" style={{marginLeft:10}}>先完成选稿，再开始修改。</span>}</section>}
    {msg&&<div className="card" style={{marginBottom:16}}>{msg}{nextUrl&&<div style={{marginTop:10}}><a className="button-link" href={nextUrl}>去做视觉 →</a></div>}</div>}
    {item.archive?.moments_caption&&<div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">朋友圈一句话</span><span className="pill">归档 {item.archive.drive_status==='synced'?'已完成':item.archive.drive_status==='failed'?'失败':'待设置'}</span></div><h2 style={{marginTop:10}}>转发朋友圈</h2><p style={{fontSize:17,lineHeight:1.7}}>{item.archive.moments_caption}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(item.archive.moments_caption);setMsg('朋友圈文案已复制。')}catch{setMsg('复制失败，请手动复制。')}}}>复制朋友圈文案</button>{item.archive.drive_folder_url&&<a className="button-link secondary" href={item.archive.drive_folder_url} target="_blank">打开归档文件夹 ↗</a>}</div>{item.archive.drive_last_error&&<p className="muted" style={{marginBottom:0}}>{item.archive.drive_last_error}</p>}</div>}
    {awaiting&&<section className="card" id="choose" style={{marginBottom:16}}><h2>选稿</h2><p>不要猜哪篇来自哪条路径，只回答：哪一篇最接近你愿意继续修改、最后发布的版本？每一轮顺序都会变化。</p><div className="grid">{steps.candidates.map((c:any)=><div className="card span-4" key={c.label}><h2>草稿 {c.label}</h2><textarea value={c.body} readOnly style={{minHeight:520}}/><button disabled={busy} onClick={()=>choose(c.label)} style={{marginTop:10}}>选这篇继续</button></div>)}</div><div style={{marginTop:12}}><button className="secondary" disabled={busy} onClick={()=>choose('NONE')}>三篇都不合适</button></div></section>}
    {rejected&&<div className="card"><h2>这一组草稿先放下</h2><p className="muted">你可以修改观点/素材后，再准备一组新的草稿。</p></div>}
    {selected&&chosen&&<><section className="card" id="drafts" style={{marginBottom:16}}><h2>选中的草稿</h2><div className="meta">{steps.candidates.map((c:any)=><span className="pill" key={c.label}>草稿 {c.label} · {writerName[c.writerKey]||'写作路径'}{c.id===steps.winner_variant_id?' · 已选':''}</span>)}</div></section><div className="split" id="final"><div className="card"><h2>选中的草稿 · {chosen.label}</h2><textarea value={chosen.body} readOnly/></div><div className="card"><h2>最终正文 / 定稿</h2><textarea value={finalText} onChange={e=>setFinal(e.target.value)}/><div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button onClick={save} disabled={busy||!finalText.trim()}>保存定稿</button>{hasFinal&&<><button className="secondary" onClick={()=>label('worth_learning')}>值得长期参考</button><button className="secondary" onClick={()=>label('one_off')}>单篇修改</button><button className="secondary" onClick={()=>label('fact_correction')}>事实纠正</button></>}</div></div></div></>}
    {(item.observations||[]).length>0&&selected&&<div className="card" style={{marginTop:16}}><h2>修改对照</h2>{item.observations.slice(0,12).map((o:any)=><p key={o.id}><span className="diff-old">{o.before_text}</span> → <span className="diff-new">{o.after_text}</span> · {o.explanation}</p>)}</div>}
  </>;
}
