'use client';
import {useEffect,useState} from 'react';
const writerName:any={control:'Control · 基础原稿',human_writing:'Human Writing',ultimate_fusion:'Ultimate Fusion + VOX Learned'};
export default function EditorClient(){
  const[item,setItem]=useState<any>(null),[viewpoint,setViewpoint]=useState(''),[finalText,setFinal]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[nextUrl,setNextUrl]=useState('');
  const load=async()=>{const id=new URLSearchParams(location.search).get('id');const r=await fetch(`/api/content${id?`?id=${encodeURIComponent(id)}`:''}`,{cache:'no-store'});const x=(await r.json()).item;setItem(x);if(x){setViewpoint(x.user_raw_input||'');const winner=(x.versions||[]).filter((v:any)=>v.version_type==='candidate'&&v.candidate_set_id).at(-1);const finals=(x.versions||[]).filter((v:any)=>v.version_type==='final');const latestFinal=finals.at(-1);const useFinal=winner&&latestFinal&&new Date(latestFinal.created_at)>=new Date(winner.created_at);setFinal(useFinal?latestFinal.body:(winner?.body||''))}};
  useEffect(()=>{load()},[]);
  if(!item)return <div className="card">还没有内容任务。先去「选题」里点“就写这个”。</div>;
  const blind=item.blindSet;const generating=blind?.status==='generating';const awaiting=blind?.status==='awaiting_choice';const selected=blind?.status==='winner_selected';const rejected=blind?.status==='rejected_all';
  const winner=selected?(blind.candidates||[]).find((c:any)=>c.id===blind.winner_variant_id):null;
  const generate=async()=>{setBusy(true);setMsg('正在生成第 1/3 份隐藏稿件…');let last:any=null;for(let i=0;i<3;i++){const r=await fetch('/api/content/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,viewpoint})});const x=await r.json();last=x;if(!x.ok){setMsg(x.needsKey?'Kimi Key 未配置。':'生成中断：'+x.error+'。已经成功的隐藏稿件会保留，下次只补缺失分支。');break}if(x.complete){setMsg('三份盲选稿已生成。先别猜来源，只选离“你会发出去”最近的一篇。');break}setMsg(`已完成 ${x.generatedCount}/3，正在继续生成下一份；三篇齐全之前不会展示正文。`)}setBusy(false);await load()};
  const choose=async(choice:string)=>{setBusy(true);const r=await fetch('/api/content/choose',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,setId:blind.id,choice})});const x=await r.json();if(x.ok){if(choice==='NONE')setMsg('已记录：三篇都不行。这个结果只进入 Writer Preference，不进入风格学习。可以重新生成一轮。');else{const w=x.set.candidates.find((c:any)=>c.id===x.set.winner_variant_id);setFinal(w?.body||'');setMsg(`已揭晓：你选的 ${choice} = ${writerName[w?.writerKey]||w?.writerKey}。现在只修改 Winner。`)}}else setMsg('选择失败：'+x.error);setBusy(false);await load()};
  const save=async()=>{setBusy(true);const r=await fetch('/api/content/final',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,finalText})});const x=await r.json();setMsg(x.ok?`Final 已保存。只比较 Winner → Final，共生成 ${x.observations.length} 条学习观察。接下来进入平台内容制作。`:'保存失败：'+x.error);if(x.ok)setNextUrl(x.nextUrl||`/publish?id=${item.id}`);setBusy(false);await load()};
  const label=async(label:string)=>{const r=await fetch('/api/content/label',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.id,label})});const x=await r.json();setMsg(x.ok?`已标记：${label}${x.proposalId?'；形成新的 Blind Skill Proposal':''}`:'标记失败');await load()};
  const hasFinal=(item.versions||[]).some((v:any)=>v.version_type==='final'&&winner&&new Date(v.created_at)>=new Date((item.versions||[]).filter((x:any)=>x.version_type==='candidate'&&x.candidate_set_id).at(-1)?.created_at||0));
  return <>
    <div className="card" style={{marginBottom:16}}><div className="muted" style={{fontSize:12}}>关联热点 · 仅用于进入这条写作任务，不会自动传给 Writer</div><h2 style={{marginTop:6}}>{item.topic_title}</h2><p className="muted" style={{marginBottom:0}}>本次生成只读取下方 Content Brief；旧标题、旧来源、旧 Candidate/Final 都不会进入生成上下文。</p></div>
    <div className="card" style={{marginBottom:16}}><h2>Content Brief · 你的原始观点 / 口述素材</h2><textarea value={viewpoint} onChange={e=>setViewpoint(e.target.value)} placeholder="写你的判断、例子、口述原话。三个 Writer 会拿到完全相同的 Brief。"/><button onClick={generate} disabled={busy||!viewpoint.trim()||awaiting} style={{marginTop:10}}>{busy?'处理中…':generating?'继续补齐三稿':blind?'重新生成一轮三稿':'生成三份盲选稿'}</button>{generating&&<span className="muted" style={{marginLeft:10}}>三篇齐全之前不会展示任何正文。</span>}{awaiting&&<span className="muted" style={{marginLeft:10}}>先完成这一轮盲选，避免覆盖实验。</span>}</div>
    {msg&&<div className="card" style={{marginBottom:16}}>{msg}{nextUrl&&<div style={{marginTop:10}}><a className="button-link" href={nextUrl}>进入内容制作 →</a></div>}</div>}
    {item.archive?.moments_caption&&<div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">朋友圈一句话</span><span className="pill">Drive {item.archive.drive_status==='synced'?'已归档':item.archive.drive_status==='failed'?'同步失败':'待配置'}</span></div><h2 style={{marginTop:10}}>转发朋友圈</h2><p style={{fontSize:17,lineHeight:1.7}}>{item.archive.moments_caption}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(item.archive.moments_caption);setMsg('朋友圈文案已复制。')}catch{setMsg('复制失败，请手动复制。')}}}>复制朋友圈文案</button>{item.archive.drive_folder_url&&<a className="button-link secondary" href={item.archive.drive_folder_url} target="_blank">打开 Google Drive 归档 ↗</a>}</div>{item.archive.drive_last_error&&<p className="muted" style={{marginBottom:0}}>Drive：{item.archive.drive_last_error}</p>}</div>}
    {awaiting&&<><div className="card" style={{marginBottom:16}}><h2>盲选规则</h2><p>不要判断“哪篇技巧最多”，只回答一个问题：<strong>哪篇离你愿意继续修改、最后发出去的版本最近？</strong> A/B/C 的来源每轮随机。</p></div><div className="grid">{blind.candidates.map((c:any)=><div className="card span-4" key={c.label}><h2>版本 {c.label}</h2><textarea value={c.body} readOnly style={{minHeight:520}}/><button disabled={busy} onClick={()=>choose(c.label)} style={{marginTop:10}}>选 {c.label} 继续改</button></div>)}</div><div style={{marginTop:12}}><button className="secondary" disabled={busy} onClick={()=>choose('NONE')}>三篇都不行</button></div></>}
    {rejected&&<div className="card"><h2>这一轮：都不行</h2><div className="meta">{blind.candidates.map((c:any)=><span className="pill" key={c.label}>{c.label} = {writerName[c.writerKey]||c.writerKey}</span>)}</div><p className="muted">已记录为 routing preference，不会拿这轮生成风格 Diff。</p></div>}
    {selected&&winner&&<><div className="card" style={{marginBottom:16}}><h2>盲选已揭晓</h2><div className="meta">{blind.candidates.map((c:any)=><span className="pill" key={c.label}>{c.label} = {writerName[c.writerKey]||c.writerKey}{c.id===blind.winner_variant_id?' · Winner':''}</span>)}</div></div><div className="split"><div className="card"><h2>Winner · {winner.label} · {writerName[winner.writerKey]||winner.writerKey}</h2><textarea value={winner.body} readOnly/></div><div className="card"><h2>Final · 你的版本</h2><textarea value={finalText} onChange={e=>setFinal(e.target.value)}/><div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button onClick={save} disabled={busy||!finalText.trim()}>保存 Final</button>{hasFinal&&<><button className="secondary" onClick={()=>label('worth_learning')}>值得长期学习</button><button className="secondary" onClick={()=>label('one_off')}>单篇修改</button><button className="secondary" onClick={()=>label('fact_correction')}>事实纠错</button></>}</div></div></div></>}
    {(item.observations||[]).length>0&&selected&&<div className="card" style={{marginTop:16}}><h2>Winner → Final Diff</h2>{item.observations.slice(0,12).map((o:any)=><p key={o.id}><span className="diff-old">{o.before_text}</span> → <span className="diff-new">{o.after_text}</span> · {o.explanation}</p>)}</div>}
  </>;
}
