'use client';
import{useEffect,useRef,useState}from'react';

const labels:any={xiaohongshu:'小红书',douyin:'抖音',wechat:'公众号草稿'},pList=['xiaohongshu','douyin','wechat'];
const jobStatusLabels:any={uploading:'上传中',ready:'待发布',publishing:'发布中',completed:'已完成',partial:'部分成功',failed:'失败'};
const resultStatusLabels:any={pending:'待执行',running:'执行中',succeeded:'成功',failed:'失败',skipped:'未选择'};

async function jsonWithTimeout(url:string,init:RequestInit={},timeoutMs=15000){const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...init,signal:controller.signal}),json=await response.json();return{response,json}}finally{window.clearTimeout(timer)}}
function matchingFiles(job:any,selected:File[]){const used=new Set<number>();return(job.files||[]).map((meta:any)=>{if(meta.ready)return{meta,file:null};const index=selected.findIndex((file,i)=>!used.has(i)&&file.name===meta.name&&file.type===meta.type&&file.size===Number(meta.size));if(index<0)return{meta,file:null};used.add(index);return{meta,file:selected[index]}})}
function uploadOne(jobId:string,fileId:string,file:File,onProgress:(loaded:number,total:number)=>void){return new Promise<any>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',`/api/quick-publish/upload?job=${encodeURIComponent(jobId)}&file=${encodeURIComponent(fileId)}`);xhr.timeout=10*60*1000;xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(e.loaded,e.total)};xhr.onload=()=>{let x:any;try{x=JSON.parse(xhr.responseText||'{}')}catch{x={}}if(xhr.status>=200&&xhr.status<300&&x.ok)return resolve(x.job);reject(new Error(x.error||`上传失败（HTTP ${xhr.status}）`))};xhr.onerror=()=>reject(new Error('网络中断，素材没有上传完成'));xhr.ontimeout=()=>reject(new Error('素材上传超过 10 分钟，已超时，请重试'));xhr.onabort=()=>reject(new Error('素材上传已取消'));xhr.send(file)})}
function completionMessage(job:any){if(job.terminalMode==='dry_run_local')return`任务 ${job.id} 已完成测试模式：${job.externalWriteOccurred===false?'测试模式，不会写入外部平台。':'请检查终态详情。'}`;const failed=(job.platforms||[]).filter((p:string)=>job.results[p]?.status!=='succeeded');return failed.length?`任务 ${job.id} 已结束，失败：${failed.map((p:string)=>labels[p]).join('、')}。可重试失败平台。`:`任务 ${job.id} 已完成。公众号已进入草稿箱。`}

export default function QuickPublishClient(){
  const input=useRef<HTMLInputElement>(null),[files,setFiles]=useState<File[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[tags,setTags]=useState(''),[platforms,setPlatforms]=useState<string[]>([]),[drag,setDrag]=useState(false),[busy,setBusy]=useState(''),[progress,setProgress]=useState(0),[msg,setMsg]=useState(''),[job,setJob]=useState<any>(null),[status,setStatus]=useState<any>(null),[history,setHistory]=useState<any[]>([]);
  const load=async(id?:string)=>{try{const x=await(await fetch(`/api/quick-publish/status${id?`?id=${encodeURIComponent(id)}`:''}`,{cache:'no-store'})).json();if(!x.ok)return;setStatus(x.status);setHistory(x.items||[]);const persisted=x.job||(!id?(x.items||[]).find((item:any)=>['uploading','ready','publishing'].includes(item.status)):null);if(id&&x.job&&job?.id===id&&job.status==='publishing'&&x.job.status!=='publishing')setMsg(completionMessage(x.job));if(persisted)setJob((current:any)=>!current||current.id===persisted.id?persisted:current)}catch(e:any){setMsg(`状态读取失败：${e?.message||e}`)}};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!job||job.status!=='publishing')return;const timer=window.setInterval(()=>load(job.id),2000);return()=>window.clearInterval(timer)},[job?.id,job?.status]);
  const addFiles=(xs:File[])=>{const next=xs.filter(f=>f.type.startsWith('image/')||f.type.startsWith('video/'));if(!next.length)return;const all=[...files,...next],videos=all.filter(f=>f.type.startsWith('video/')),images=all.filter(f=>f.type.startsWith('image/'));if(videos.length>1)return setMsg('一次只能放 1 个视频。');if(videos.length&&images.length>1)return setMsg('视频模式可以额外带 1 张封面图。');if(!videos.length&&images.length>18)return setMsg('图文一次最多 18 张图片。');setFiles(all);setMsg('')};
  const toggle=(p:string)=>setPlatforms(x=>x.includes(p)?x.filter(v=>v!==p):[...x,p]);
  const uploadJob=async(existing:any,selected:File[])=>{const matches=matchingFiles(existing,selected),pending=matches.filter((x:any)=>!x.meta.ready),missing=pending.filter((x:any)=>!x.file);if(missing.length)throw Error(`任务 ${existing.id} 仍缺少：${missing.map((x:any)=>x.meta.name).join('、')}。请重新选择同名、同类型、同大小的文件后重试。`);let current=existing,ready=current.files.filter((x:any)=>x.ready).length;setProgress(Math.round(ready/current.files.length*100));for(let i=0;i<pending.length;i++){const item=pending[i];const base=ready+i;const next=await uploadOne(current.id,item.meta.id,item.file,(loaded,total)=>setProgress(Math.round(((base+loaded/total)/current.files.length)*100)));current=next||current;ready=current.files.filter((x:any)=>x.ready).length;setJob(current)}setProgress(100);return current};
  const createAndUpload=async()=>{setBusy('upload');setProgress(0);setMsg('正在创建发布任务…');let current:any=null;try{const{response,json}=await jsonWithTimeout('/api/quick-publish/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,body,tags,platforms,files:files.map(f=>({name:f.name,type:f.type,size:f.size}))})},20000);if(!response.ok||!json.ok)throw Error(json.error||'创建发布任务失败');current=json.job;setJob(current);setMsg(`任务 ${current.id} 已创建，开始上传素材…`);current=await uploadJob(current,files);setJob(current);setMsg(`素材已上传。任务 ${current.id} 状态：待发布。检查无误后点击一键发布。`)}catch(e:any){if(current)try{const s=await(await fetch(`/api/quick-publish/status?id=${encodeURIComponent(current.id)}`,{cache:'no-store'})).json();if(s.job){current=s.job;setJob(current)}}catch{}setMsg(e?.name==='AbortError'?'创建任务请求超时；请刷新查看是否已创建任务。':`上传失败：${e?.message||e}`)}setBusy('');await load(current?.id)};
  const resumeUpload=async()=>{if(!job)return;if(!files.length){setMsg(`任务 ${job.id} 尚未完成。请重新选择未上传的原文件后，再点击继续上传。`);return}setBusy('upload');setMsg(`正在继续上传任务 ${job.id}…`);let current=job;try{current=await uploadJob(current,files);setJob(current);setMsg(`素材已上传。任务 ${current.id} 状态：待发布。检查无误后点击一键发布。`)}catch(e:any){try{const s=await(await fetch(`/api/quick-publish/status?id=${encodeURIComponent(current.id)}`,{cache:'no-store'})).json();if(s.job){current=s.job;setJob(current)}}catch{}setMsg(`上传失败：${e?.message||e}`)}setBusy('');await load(current.id)};
  const publish=async()=>{if(!job||job.status==='completed'||job.status==='publishing')return;const retry=job.status==='partial'||job.status==='failed',dryRun=!!status?.dryRun;const destinations=job.platforms.map((p:string)=>labels[p]).join('、'),prompt=dryRun?`确认模拟发布「${job.title}」到 ${destinations}？测试模式不会写入外部平台。`: `${retry?'确认重试失败平台':'确认把'}「${job.title}」${retry?'的失败平台':''}发送到 ${destinations}？`;if(!confirm(prompt))return;setBusy('publish');setMsg(`正在提交任务 ${job.id}，请不要重复点击。`);try{const{response,json}=await jsonWithTimeout('/api/quick-publish/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jobId:job.id,retryFailed:retry})},20000);if(!response.ok||!json.ok)throw Error(json.error||'提交发布任务失败');setJob(json.job);setMsg(`任务 ${json.job.id} 已提交，当前状态：${jobStatusLabels[json.job.status]||json.job.status}。页面会自动回读最终结果。`)}catch(e:any){setMsg(e?.name==='AbortError'?`提交请求超时；任务 ${job.id} 可能仍在执行，页面会继续回读状态。`:`发布失败：${e?.message||e}`);await load(job.id)}setBusy('')};
  const account=async(action:string,p:string)=>{setBusy(`${action}:${p}`);try{const x=await(await fetch('/api/quick-publish/account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,platform:p})})).json();if(!x.ok)throw Error(x.error);setMsg(action==='login'?`已在发布主机启动 ${labels[p]} 登录窗口。`:x.valid?`${labels[p]} 登录态有效。`:`${labels[p]} 登录态已失效。`)}catch(e:any){setMsg(e.message)}setBusy('');await load()};
  const reset=()=>{setFiles([]);setTitle('');setBody('');setTags('');setPlatforms([]);setJob(null);setProgress(0);setMsg('')},kind=files.some(f=>f.type.startsWith('video/'))?'video':'images';
  const uploadMode=!job||job.status==='uploading',canResume=!!job&&job.status==='uploading',canPublish=!!job&&['ready','partial','failed'].includes(job.status);
  return <><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">外部成品</span><span className="pill">视频 / 图文</span><span className="pill">一份文案，多端使用</span>{status?.dryRun&&<span className="pill">测试模式</span>}</div><h1 style={{marginTop:10}}>上传并发布外部成品</h1><p className="muted">上传已经做好的内容，系统不改视频、不改图片。请明确选择要发布的平台；不会默认全选。</p>{status?.dryRun&&<p className="muted">测试模式，不会写入外部平台。这里只执行本机模拟，不调用任何外部发布代码。</p>}</div>
  <div className="grid"><section className="card span-8"><h2>1. 放入成品</h2><div className={`direct-drop ${drag?'is-dragging':''}`} tabIndex={0} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(Array.from(e.dataTransfer.files))}} onPaste={e=>{const xs=Array.from(e.clipboardData.files);if(xs.length){e.preventDefault();addFiles(xs)}}}><input ref={input} hidden type="file" multiple accept="image/*,video/*" onChange={e=>addFiles(Array.from(e.target.files||[]))}/><strong>{files.length?`${kind==='video'?'视频':'图文'} · 已选 ${files.length} 个文件`:'拖入视频/图片，点击选择，或直接粘贴图片'}</strong><div className="muted" style={{marginTop:6}}>图文最多 18 张；视频 1 个，可额外带 1 张封面图。</div></div>{files.length>0&&<div className="file-chips" style={{marginTop:10}}>{files.map((f,i)=><span className="file-chip" key={`${f.name}-${i}`}>{f.type.startsWith('video/')?'视频':'图片'} · {f.name}<button onClick={e=>{e.stopPropagation();setFiles(x=>x.filter((_,n)=>n!==i))}}>×</button></span>)}</div>}
  <p><strong>标题 <span className="muted">{[...title].length}/20</span></strong></p><input className="text-input" value={title} maxLength={20} onChange={e=>setTitle(e.target.value)} placeholder="三端共用标题"/><p><strong>正文 / 简介 <span className="muted">{[...body].length}/1000</span></strong></p><textarea value={body} maxLength={1000} onChange={e=>setBody(e.target.value)} placeholder="三端共用正文；不会自动删改。"/><p><strong>额外标签</strong></p><input className="text-input" value={tags} onChange={e=>setTags(e.target.value)} placeholder="例如：牛来 动画电影 配乐（固定 VOX 标签会自动附加）"/>
  <h2>2. 选择发布平台</h2><div className="platform-picks">{pList.map(p=><label key={p} className={platforms.includes(p)?'platform-pick selected':'platform-pick'}><input type="checkbox" checked={platforms.includes(p)} onChange={()=>toggle(p)}/><strong>{labels[p]}</strong><span className="muted">{p==='wechat'?'只进草稿箱':p==='douyin'&&kind==='images'?'配乐按发布设置选择':'原成品直发'}</span></label>)}</div><p className="muted"><strong>将发布到：</strong>{platforms.length?platforms.map(p=>labels[p]).join('、'):'尚未选择平台，请明确选择后继续。'}</p>
  {uploadMode?<button disabled={!!busy||(!job&&!files.length)||(!job&&!title.trim())||(!job&&!platforms.length)||(canResume&&!files.length)} onClick={canResume?resumeUpload:createAndUpload}>{busy==='upload'?(canResume?'继续上传中…':'创建并上传中…'):canResume?'继续上传任务':'上传并创建发布任务'}</button>:canPublish?<button disabled={!!busy} onClick={publish}>{busy==='publish'?'提交发布任务中…':status?.dryRun?'运行测试模式（不会写入外部平台）':job?.status==='ready'?'发布所选平台':'重试失败平台'}</button>:<button disabled>{job?.status==='publishing'?'发布任务执行中…':'任务已完成'}</button>}{job&&<button className="secondary" disabled={!!busy} onClick={reset} style={{marginLeft:8}}>新建一条</button>}{job&&['completed','partial','failed'].includes(job.status)&&<a className="button-link" href="/publish?tab=history" style={{marginLeft:8}}>查看发布结果 →</a>}{progress>0&&progress<100&&<div className="progress-track"><div className="progress-bar" style={{width:`${progress}%`}}/></div>}{msg&&<p className="muted" style={{whiteSpace:'pre-wrap'}}>{msg}</p>}</section>
  <section className="card span-4"><h2>2. 发布连接</h2><div className="connection-row"><strong>小红书</strong><span className="pill">{status?.sau?.xiaohongshuCookie?'已有登录态':'未登录'}</span></div><div className="connection-actions"><button className="secondary tiny" disabled={!!busy} onClick={()=>account('check','xiaohongshu')}>检查</button><button className="secondary tiny" disabled={!!busy} onClick={()=>account('login','xiaohongshu')}>刷新登录</button></div><div className="connection-row"><strong>抖音</strong><span className="pill">{status?.sau?.douyinCookie?'已有登录态':'未登录'}</span></div><div className="connection-actions"><button className="secondary tiny" disabled={!!busy} onClick={()=>account('check','douyin')}>检查</button><button className="secondary tiny" disabled={!!busy} onClick={()=>account('login','douyin')}>刷新登录</button></div><div className="connection-row"><strong>公众号</strong><span className="pill">{status?.wechat?.configured?'已连接':'未连接'}</span></div><p className="muted">登录刷新窗口会开在办公室这台发布主机上；平时登录态有效时，在家里无需操作它。</p><hr/><strong>远程访问</strong><p className="muted">发布主机：{status?.host||'voxmac-mini'}。家里电脑登录同一 Tailscale 后访问：<br/><code>http://100.117.201.96:3000/quick-publish</code></p></section></div>
  {job&&<div className="card" style={{marginTop:16}}><h2>当前任务</h2><div className="meta"><span className="pill">{job.kind==='video'?'视频':'图文'}</span><span className="pill">{jobStatusLabels[job.status]||job.status}</span><span className="pill" style={{wordBreak:'break-all'}}>任务 ID：{job.id}</span>{job.platforms.map((p:string)=><span className="pill" key={p}>{labels[p]} · {resultStatusLabels[job.results[p]?.status]||job.results[p]?.status}</span>)}</div>{job.files?.filter((f:any)=>f.error).map((f:any)=><p className="muted" key={f.id}>素材 {f.name}：{f.error}</p>)}{job.platforms.map((p:string)=><div key={p} className="result-row"><strong>{labels[p]}</strong><span>{resultStatusLabels[job.results[p]?.status]||job.results[p]?.status}</span>{job.results[p]?.message&&<span className="muted">{job.results[p].message}</span>}</div>)}</div>}
  {history.length>0&&<div className="card" style={{marginTop:16}}><h2>最近直发记录</h2>{history.map(h=><div className="history-line" key={h.id}><div><strong>{h.title}</strong><div className="muted">{new Date(h.createdAt).toLocaleString()} · {h.kind==='video'?'视频':'图文'}</div></div><div className="meta"><span className="pill">{jobStatusLabels[h.status]||h.status}</span>{h.platforms.map((p:string)=><span className="pill" key={p}>{labels[p]} {h.results[p]?.status==='succeeded'?'✓':h.results[p]?.status==='failed'?'×':'·'}</span>)}</div></div>)}</div>}</>
}
