'use client';import{useEffect,useRef,useState}from'react';
const labels:any={xiaohongshu:'小红书',douyin:'抖音',wechat:'公众号草稿'},pList=['xiaohongshu','douyin','wechat'];
export default function QuickPublishClient(){const input=useRef<HTMLInputElement>(null),[files,setFiles]=useState<File[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[tags,setTags]=useState(''),[platforms,setPlatforms]=useState<string[]>(pList),[drag,setDrag]=useState(false),[busy,setBusy]=useState(''),[progress,setProgress]=useState(0),[msg,setMsg]=useState(''),[job,setJob]=useState<any>(null),[status,setStatus]=useState<any>(null),[history,setHistory]=useState<any[]>([]);
const load=async()=>{const x=await(await fetch('/api/quick-publish/status',{cache:'no-store'})).json();setStatus(x.status);setHistory(x.items||[])};useEffect(()=>{load()},[]);
const addFiles=(xs:File[])=>{const next=xs.filter(f=>f.type.startsWith('image/')||f.type.startsWith('video/'));if(!next.length)return;const all=[...files,...next],videos=all.filter(f=>f.type.startsWith('video/')),images=all.filter(f=>f.type.startsWith('image/'));if(videos.length>1)return setMsg('一次只能放 1 个视频。');if(videos.length&&images.length>1)return setMsg('视频模式可以额外带 1 张封面图。');if(!videos.length&&images.length>18)return setMsg('图文一次最多 18 张图片。');setFiles(all);setMsg('')};
const toggle=(p:string)=>setPlatforms(x=>x.includes(p)?x.filter(v=>v!==p):[...x,p]);
const createAndUpload=async()=>{setBusy('upload');setProgress(0);setMsg('正在上传素材到发布主机…');try{const x=await(await fetch('/api/quick-publish/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,body,tags,platforms,files:files.map(f=>({name:f.name,type:f.type,size:f.size}))})})).json();if(!x.ok)throw Error(x.error);let current=x.job;for(let i=0;i<files.length;i++){await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',`/api/quick-publish/upload?job=${encodeURIComponent(current.id)}&file=${encodeURIComponent(current.files[i].id)}`);xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(((i+e.loaded/e.total)/files.length)*100))};xhr.onload=()=>xhr.status<300?resolve():reject(new Error(xhr.responseText||'上传失败'));xhr.onerror=()=>reject(new Error('上传失败'));xhr.send(files[i])});const s=await(await fetch(`/api/quick-publish/status?id=${encodeURIComponent(current.id)}`,{cache:'no-store'})).json();current=s.job}setJob(current);setProgress(100);setMsg('素材已上传。检查无误后点击一键发布。')}catch(e:any){setMsg(`上传失败：${e.message}`)}setBusy('');await load()};
const publish=async()=>{if(!job)return;if(!confirm(`确认把「${job.title}」发送到 ${job.platforms.map((p:string)=>labels[p]).join('、')}？`))return;setBusy('publish');setMsg('正在依次发布，请不要重复点击。');try{const x=await(await fetch('/api/quick-publish/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jobId:job.id})})).json();if(!x.ok)throw Error(x.error);setJob(x.job);const failed=x.job.platforms.filter((p:string)=>x.job.results[p]?.status!=='succeeded');setMsg(failed.length?`执行完成，失败：${failed.map((p:string)=>labels[p]).join('、')}`:'三端发布完成。公众号已进入草稿箱。')}catch(e:any){setMsg(`发布失败：${e.message}`)}setBusy('');await load()};
const account=async(action:string,p:string)=>{setBusy(`${action}:${p}`);try{const x=await(await fetch('/api/quick-publish/account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,platform:p})})).json();if(!x.ok)throw Error(x.error);setMsg(action==='login'?`已在发布主机启动 ${labels[p]} 登录窗口。`:x.valid?`${labels[p]} 登录态有效。`:`${labels[p]} 登录态已失效。`)}catch(e:any){setMsg(e.message)}setBusy('');await load()};
const reset=()=>{setFiles([]);setTitle('');setBody('');setTags('');setPlatforms(pList);setJob(null);setProgress(0);setMsg('')},kind=files.some(f=>f.type.startsWith('video/'))?'video':'images';
return <><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">成品直发</span><span className="pill">视频 / 图文</span><span className="pill">三端共用一份文案</span>{status?.dryRun&&<span className="pill">DRY RUN</span>}</div><h1 style={{marginTop:10}}>一键内容发布台</h1><p className="muted">上传已经做好的内容，系统不改视频、不改图片。小红书和抖音直接发布；公众号只写入草稿箱。视频模式下，公众号使用封面/视频首帧 + 同一份文案生成图文草稿。</p></div>
<div className="grid"><section className="card span-8"><h2>1. 放入成品</h2><div className={`direct-drop ${drag?'is-dragging':''}`} tabIndex={0} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(Array.from(e.dataTransfer.files))}} onPaste={e=>{const xs=Array.from(e.clipboardData.files);if(xs.length){e.preventDefault();addFiles(xs)}}}><input ref={input} hidden type="file" multiple accept="image/*,video/*" onChange={e=>addFiles(Array.from(e.target.files||[]))}/><strong>{files.length?`${kind==='video'?'视频':'图文'} · 已选 ${files.length} 个文件`:'拖入视频/图片，点击选择，或直接粘贴图片'}</strong><div className="muted" style={{marginTop:6}}>图文最多 18 张；视频 1 个，可额外带 1 张封面图。</div></div>{files.length>0&&<div className="file-chips" style={{marginTop:10}}>{files.map((f,i)=><span className="file-chip" key={`${f.name}-${i}`}>{f.type.startsWith('video/')?'视频':'图片'} · {f.name}<button onClick={e=>{e.stopPropagation();setFiles(x=>x.filter((_,n)=>n!==i))}}>×</button></span>)}</div>}
<p><strong>标题 <span className="muted">{[...title].length}/20</span></strong></p><input className="text-input" value={title} maxLength={20} onChange={e=>setTitle(e.target.value)} placeholder="三端共用标题"/><p><strong>正文 / 简介 <span className="muted">{[...body].length}/1000</span></strong></p><textarea value={body} maxLength={1000} onChange={e=>setBody(e.target.value)} placeholder="三端共用正文；不会自动删改。"/><p><strong>额外标签</strong></p><input className="text-input" value={tags} onChange={e=>setTags(e.target.value)} placeholder="例如：牛来 动画电影 配乐（固定 VOX 标签会自动附加）"/>
<div className="platform-picks">{pList.map(p=><label key={p} className={platforms.includes(p)?'platform-pick selected':'platform-pick'}><input type="checkbox" checked={platforms.includes(p)} onChange={()=>toggle(p)}/><strong>{labels[p]}</strong><span className="muted">{p==='wechat'?'只进草稿箱':p==='douyin'&&kind==='images'?'图文自动搜 Cory Wong 配乐':'原成品直发'}</span></label>)}</div>
{!job?<button disabled={!!busy||!files.length||!title.trim()||!platforms.length} onClick={createAndUpload}>{busy==='upload'?'上传中…':'上传并创建发布任务'}</button>:<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy||status?.dryRun||job.status==='completed'} onClick={publish}>{busy==='publish'?'三端发布中…':status?.dryRun?'DRY RUN：真实发布锁定':'一键发布所选平台'}</button><button className="secondary" disabled={!!busy} onClick={reset}>新建一条</button></div>}{progress>0&&progress<100&&<div className="progress-track"><div className="progress-bar" style={{width:`${progress}%`}}/></div>}{msg&&<p className="muted" style={{whiteSpace:'pre-wrap'}}>{msg}</p>}</section>
<section className="card span-4"><h2>2. 发布连接</h2><div className="connection-row"><strong>小红书</strong><span className="pill">{status?.sau?.xiaohongshuCookie?'已有登录态':'未登录'}</span></div><div className="connection-actions"><button className="secondary tiny" disabled={!!busy} onClick={()=>account('check','xiaohongshu')}>检查</button><button className="secondary tiny" disabled={!!busy} onClick={()=>account('login','xiaohongshu')}>刷新登录</button></div><div className="connection-row"><strong>抖音</strong><span className="pill">{status?.sau?.douyinCookie?'已有登录态':'未登录'}</span></div><div className="connection-actions"><button className="secondary tiny" disabled={!!busy} onClick={()=>account('check','douyin')}>检查</button><button className="secondary tiny" disabled={!!busy} onClick={()=>account('login','douyin')}>刷新登录</button></div><div className="connection-row"><strong>公众号</strong><span className="pill">{status?.wechat?.configured?'API 已配置':'未配置'}</span></div><p className="muted">登录刷新窗口会开在办公室这台发布主机上；平时登录态有效时，在家里无需操作它。</p><hr/><strong>远程访问</strong><p className="muted">发布主机：{status?.host||'voxmac-mini'}。家里电脑登录同一 Tailscale 后访问：<br/><code>http://100.117.201.96:3000/quick-publish</code></p></section></div>
{job&&<div className="card" style={{marginTop:16}}><h2>当前任务</h2><div className="meta"><span className="pill">{job.kind==='video'?'视频':'图文'}</span><span className="pill">{job.status}</span>{job.platforms.map((p:string)=><span className="pill" key={p}>{labels[p]} · {job.results[p]?.status}</span>)}</div>{job.platforms.map((p:string)=><div key={p} className="result-row"><strong>{labels[p]}</strong><span>{job.results[p]?.status}</span>{job.results[p]?.message&&<span className="muted">{job.results[p].message}</span>}</div>)}</div>}
{history.length>0&&<div className="card" style={{marginTop:16}}><h2>最近直发记录</h2>{history.map(h=><div className="history-line" key={h.id}><div><strong>{h.title}</strong><div className="muted">{new Date(h.createdAt).toLocaleString()} · {h.kind==='video'?'视频':'图文'}</div></div><div className="meta"><span className="pill">{h.status}</span>{h.platforms.map((p:string)=><span className="pill" key={p}>{labels[p]} {h.results[p]?.status==='succeeded'?'✓':h.results[p]?.status==='failed'?'×':'·'}</span>)}</div></div>)}</div>}</>}
