'use client';import{useEffect,useState}from'react';
import{ContentJourney}from'../../../components/ContentJourney';
const platformNames:any={wechat:'公众号',xiaohongshu:'小红书',douyin:'抖音'};
const actionNames:any={draft:'写入草稿',publish:'正式发布'};
export default function PublishClient(){
 const[item,setItem]=useState<any>(null),[pub,setPub]=useState<any>(null),[pre,setPre]=useState<any>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState('');const id=typeof window!=='undefined'?new URLSearchParams(location.search).get('id')||'':'';
 const load=async()=>{if(!id)return;const[r,s]=await Promise.all([fetch(`/api/release?id=${encodeURIComponent(id)}`,{cache:'no-store'}),fetch(`/api/release/publish/status?id=${encodeURIComponent(id)}`,{cache:'no-store'})]),a=await r.json(),b=await s.json();if(a.ok)setItem(a.item);else setMsg(a.error);if(b.ok)setPub(b)};useEffect(()=>{load()},[id]);
 const copy=async()=>{try{await navigator.clipboard.writeText(item?.master?.social_caption||item?.master?.body||'');setMsg('简介已复制。')}catch{setMsg('复制失败，请手动复制。')}};
 const preflight=async()=>{setBusy('preflight');try{const r=await fetch(`/api/release/publish/preflight?id=${encodeURIComponent(id)}`,{cache:'no-store'}),x=await r.json();if(!x.ok)throw Error(x.error);setPre(x);const bad=[];if(!x.wechat?.valid)bad.push('公众号');if(!x.xiaohongshu?.valid)bad.push('小红书登录');if(!x.douyin?.valid)bad.push('抖音登录');if(!x.xiaohongshu?.bodyOk)bad.push(`小红书正文 ${x.xiaohongshu.bodyChars}/1000 字`);if(!x.douyin?.bodyOk)bad.push(`抖音正文 ${x.douyin.bodyChars}/1000 字`);if(!x.content?.sourceLock)bad.push('统一版式来源');if(!x.content?.pagesReady)bad.push('平台页数');setMsg(bad.length?`预检未通过：${bad.join('、')}`:'三端连接和素材预检通过。')}catch(e:any){setMsg(`预检失败：${e.message}`)}setBusy('')};
 const post=async(url:string,body:any)=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),x=await r.json();if(!x.ok)throw Error(x.error||'操作失败');return x};
 const local=async(action:'login'|'check'|'publish',platform:'douyin'|'xiaohongshu'|'wechat')=>{if(action==='publish'&&!confirm(platform==='wechat'?'确认把当前版式写入公众号草稿箱？':`确认把当前已确认图文发布到${platform==='douyin'?'抖音':'小红书'}？`))return;setBusy(`${action}:${platform}`);try{if(action==='login'){await post('/api/release/publish/local/login',{platform});setMsg(`已启动${platform==='douyin'?'抖音':'小红书'}登录窗口。完成后点“检查登录”。`)}else if(action==='check'){const x=await post('/api/release/publish/local/check',{platform});setMsg(x.valid?`${platform==='douyin'?'抖音':'小红书'}登录态有效。`:`${platform==='douyin'?'抖音':'小红书'}还没有有效登录态，请重新登录。`)}else{const x=await post('/api/release/publish/local/run',{contentId:id,platform});setMsg(platform==='wechat'?'已写入公众号草稿。':`${platform==='douyin'?'抖音':'小红书'}发布任务成功：${x.engine}`);await load()}}catch(e:any){setMsg(`操作失败：${e.message}`)}setBusy('');await load()};
 const wechat=async(action:'draft'|'publish')=>{if(action==='publish'&&!confirm('确认提交公众号正式发布？'))return;setBusy('wx:'+action);try{await post('/api/release/publish/wechat',{contentId:id,action});setMsg(action==='draft'?'已写入公众号草稿。':'公众号已提交发布。');await load()}catch(e:any){setMsg(`公众号操作失败：${e.message}`)}setBusy('')};
 if(!item)return <div className="card"><h2>发布</h2><p className="muted">{msg||'正在读取发布素材…'}</p></div>;
 if(item.publish_state!=='ready_to_publish')return <><ContentJourney contentId={id} current="publish" doneSteps={['viewpoint','draft','choose','final','visual']}/><div className="card"><h2>还不能进入发布</h2><p className="muted">请先确认小红书和抖音的最终排版版本。</p><a className="button-link" href={`/release?id=${encodeURIComponent(id)}`}>返回发布前准备 →</a></div></>;
 const c=pub?.connections||{},l=pub?.local||{},jobs=pub?.jobs||[],draft=jobs.find((j:any)=>j.platform==='wechat'&&j.action==='draft'&&j.status==='succeeded'),dry=!!l.dryRun;
 const social=(platform:'xiaohongshu'|'douyin',title:string,portal:string,cookie:boolean)=><section className="card span-4"><div className="meta"><span className="pill">{title}</span><span className="pill">{cookie?'已保存登录态':'未登录'}</span></div><h2>{title}</h2><p className="muted">使用已连接的发布账号，把当前确认的 3:4 图片和简介交给平台；图片内容来自已经确认的统一版式。</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary" disabled={!!busy} onClick={()=>local('login',platform)}>{busy===`login:${platform}`?'启动中…':'登录 / 刷新账号'}</button><button className="secondary" disabled={!!busy} onClick={()=>local('check',platform)}>{busy===`check:${platform}`?'检查中…':'检查登录'}</button><button disabled={!!busy||dry||!cookie} onClick={()=>local('publish',platform)}>{busy===`publish:${platform}`?'发布中…':`发布到${title}`}</button><a className="button-link secondary" href={`/api/release/export?id=${encodeURIComponent(id)}&platform=${platform}`}>下载发布包</a><button className="secondary" onClick={copy}>复制简介</button><a className="button-link secondary" href={portal} target="_blank">打开{title}后台</a></div>{dry&&<p className="muted">测试模式，不会写入外部平台。</p>}</section>;
 return <><ContentJourney contentId={id} current="publish" doneSteps={['viewpoint','draft','choose','final','visual']}/><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">发布</span>{dry&&<span className="pill">测试模式</span>}<span className="pill">素材已确认</span></div><h1 style={{fontSize:28,marginTop:12}}>发布内容</h1><p className="muted">所有平台都只读取已经确认的正文和图片。正式发布前可以先做预检；当前若为测试模式，不会写入外部平台。</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={preflight} disabled={!!busy}>{busy==='preflight'?'预检中…':'发布前预检'}</button><a className="button-link secondary" href={`/release?id=${encodeURIComponent(id)}`}>← 返回发布前准备</a></div></div>{pre&&<div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">公众号 {pre.wechat?.valid?'✓':'×'}</span><span className="pill">小红书登录 {pre.xiaohongshu?.valid?'✓':'×'}</span><span className="pill">抖音登录 {pre.douyin?.valid?'✓':'×'}</span><span className="pill">小红书正文 {pre.xiaohongshu?.bodyChars}/1000</span><span className="pill">抖音正文 {pre.douyin?.bodyChars}/1000</span><span className="pill">版式来源 {pre.content?.sourceLock?'✓':'×'}</span><span className="pill">平台页数 {pre.content?.pagesReady?'✓':'×'}</span></div>{pre.wechat?.error&&<p className="muted">公众号：{pre.wechat.error}</p>}{!pre.xiaohongshu?.bodyOk&&<p className="muted">当前正文超过小红书图文正文 1000 字预检限制；系统不会自动截断。</p>}{!pre.douyin?.bodyOk&&<p className="muted">当前正文超过抖音图文 1000 字预检限制；系统不会自动截断或改写。</p>}</div>}{msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}
 <div className="grid"><section className="card span-4"><div className="meta"><span className="pill">公众号</span><span className="pill">{l.wechatsync?.installed?'发布工具已连接':'发布工具待连接'}</span></div><h2>公众号</h2><p className="muted">把确认后的公众号正文写入草稿箱；正式发布前仍会保留人工确认。</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy||dry||!l.wechatsync?.installed||!l.wechatsync?.tokenConfigured} onClick={()=>local('publish','wechat')}>{busy==='publish:wechat'?'同步中…':'写入草稿箱'}</button>{c.wechat?.backup?.configured&&<button disabled={!!busy||dry} onClick={()=>wechat('draft')}>{busy==='wx:draft'?'推送中…':'备用方式写入草稿'}</button>}{draft&&c.wechat?.backup?.configured&&<button disabled={!!busy||dry} onClick={()=>wechat('publish')}>提交正式发布</button>}<a className="button-link secondary" href={`/api/release/export?id=${encodeURIComponent(id)}&platform=wechat`}>下载发布包</a><a className="button-link secondary" href={c.wechat?.portal||'https://mp.weixin.qq.com/'} target="_blank">打开公众号后台</a></div>{!l.wechatsync?.tokenConfigured&&<p className="muted">发布工具还没有连接，请先完成本机登录设置。</p>}{dry&&<p className="muted">测试模式，不会写入外部平台。</p>}</section>{social('xiaohongshu','小红书',c.xiaohongshu?.portal||'https://creator.xiaohongshu.com/',!!l.sau?.xiaohongshuCookie)}{social('douyin','抖音',c.douyin?.portal||'https://creator.douyin.com/',!!l.sau?.douyinCookie)}</div>
 {jobs.length>0&&<div className="card" style={{marginTop:16}}><h2>发布记录</h2>{jobs.map((j:any)=><div key={j.id} style={{padding:'8px 0',borderBottom:'1px solid var(--line)'}}><strong>{platformNames[j.platform]||j.platform} · {actionNames[j.action]||j.action}</strong> <span className="muted">{j.status}{j.remote_id?` · ${j.remote_id}`:''}{j.error_text?` · ${j.error_text}`:''}</span></div>)}</div>}</>;
}
