'use client';import{useEffect,useRef,useState}from'react';
import ImageDropPaste from '../../components/ImageDropPaste';
import {ContentJourney} from '../../components/ContentJourney';
const names:any={xiaohongshu:'小红书 3:4 排版',douyin:'抖音图文 3:4 排版'};
async function upload(packageId:string,files:File[]){if(!files.length)return[];const f=new FormData();f.append('packageId',packageId);files.forEach(x=>f.append('files',x));const r=await(await fetch('/api/publish/upload',{method:'POST',body:f})).json();if(!r.ok)throw Error(r.error||'上传失败');return r.files||[]}
export default function ReleaseClient(){const[item,setItem]=useState<any>(null),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[notes,setNotes]=useState<any>({}),[files,setFiles]=useState<any>({});const auto=useRef(false),id=typeof window!=='undefined'?new URLSearchParams(location.search).get('id')||'':'';
const load=async()=>{const x=await(await fetch(id?`/api/release?id=${encodeURIComponent(id)}`:'/api/release',{cache:'no-store'})).json();if(x.ok)setItem(x.item);else setMsg(x.error)};useEffect(()=>{load()},[id]);
const waitFor=async(platform:string)=>{for(let i=0;i<150;i++){await new Promise(r=>setTimeout(r,2000));const x=await(await fetch(id?`/api/release?id=${encodeURIComponent(id)}`:'/api/release',{cache:'no-store'})).json();if(!x.ok)continue;setItem(x.item);const a=x.item.adaptations?.find((v:any)=>v.platform===platform);if(a?.status==='ready'||a?.status==='approved'||a?.status==='failed')return a}return null};
const adapt=async(platform:string,instruction='')=>{if(!item?.master)return;setBusy(platform);setMsg(`${names[platform]}正在根据统一版式重新排版…`);try{const refs=await upload(item.master.id,files[platform]||[]),x=await(await fetch('/api/release/adapt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.content_id,platform,instruction,uploadedAssets:refs})})).json();if(!x.ok)throw Error(x.error);const done=await waitFor(platform);if(done?.status==='failed')throw Error(done.error_text||'适配失败');setNotes((v:any)=>({...v,[platform]:''}));setFiles((v:any)=>({...v,[platform]:[]}));setMsg(done?`${names[platform]}已生成。`:`${names[platform]}仍在后台生成，可稍后刷新查看。`)}catch(e:any){setMsg(`${names[platform]}失败：${e.message}`)}setBusy('');await load()};
useEffect(()=>{if(!item||auto.current||!['master_approved','platform_adapting'].includes(item.publish_state))return;const missing=['xiaohongshu','douyin'].filter(p=>!item.adaptations?.some((a:any)=>a.platform===p));if(!missing.length)return;auto.current=true;(async()=>{for(const p of missing){setBusy(p);setMsg(`${names[p]}正在根据统一版式自动排版…`);const x=await(await fetch('/api/release/adapt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.content_id,platform:p})})).json();if(!x.ok){setMsg(`${names[p]}自动排版失败：${x.error}`);break}const done=await waitFor(p);if(done?.status==='failed'){setMsg(`${names[p]}自动排版失败：${done.error_text||'unknown'}`);break}}setBusy('');await load()})()},[item?.content_id,item?.publish_state]);
const approve=async(a:any)=>{setBusy('approve:'+a.platform);const x=await(await fetch('/api/release/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:a.id})})).json();setMsg(x.ok?`${names[a.platform]}已确认。`:`确认失败：${x.error}`);setBusy('');await load()};
if(!item)return <div className="card"><h2>发布前准备</h2><p className="muted">{msg||'正在读取统一版式…'}</p></div>;
return <><ContentJourney contentId={item.content_id} current="publish" doneSteps={['viewpoint','draft','choose','final','visual']}/><div className="card" style={{marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="meta"><span className="pill">1 定稿 ✓</span><span className="pill">2 统一版式 ✓</span><span className="pill">3 平台排版</span><span className="pill">4 发布准备</span></div><h1 style={{fontSize:28,marginTop:12}}>发布前准备</h1></div>{item.publish_state==='ready_to_publish'&&<a className="button-link" href={`/release/publish?id=${encodeURIComponent(item.content_id)}`} style={{fontSize:16,padding:'12px 18px'}}>发布内容 →</a>}</div><p className="muted">公众号与小红书共用同一个已确认版式。小红书只做 3:4 排版：正文、图注、图形文字和图片都保持一致；空间不够就增加页数。抖音图文执行同一规则。</p></div>{msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}
<div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">公众号统一版式 · 已确认</span></div><h2>{item.master?.title}</h2><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{item.masterVisual?.coverUrl&&<a className="button-link secondary" href={item.masterVisual.coverUrl} target="_blank">查看封面 ↗</a>}{item.masterVisual?.htmlUrl&&<a className="button-link secondary" href={item.masterVisual.htmlUrl} target="_blank">查看公众号正文 ↗</a>}<a className="button-link secondary" href={`/publish?id=${encodeURIComponent(item.content_id)}`}>返回修改版式</a></div></div>
<div className="grid">{['xiaohongshu','douyin'].map(platform=>{const a=item.adaptations?.find((x:any)=>x.platform===platform);return <div className="card span-12" key={platform}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><div className="meta"><span className="pill">{a?.status==='approved'?'已确认':a?.status==='ready'?'待确认':a?.status==='generating'?'生成中':a?.status==='failed'?'失败':'待生成'}</span>{a?.current_revision_no>0&&<span className="pill">R{a.current_revision_no}</span>}</div><h2>{names[platform]}</h2><p className="muted">1080×1440 · 只改排版 · 发布内容锁定 · 内部来源审计不出现在成品</p></div>{!a&&<button disabled={!!busy} onClick={()=>adapt(platform)}>{busy===platform?'生成中…':'生成适配'}</button>}</div>{a?.error_text&&<p className="muted">{a.error_text}</p>}{a?.files?.length>0&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginTop:14}}>{a.files.map((f:any)=><a key={f.page} href={f.pngUrl} target="_blank" style={{textDecoration:'none'}}><img src={f.pngUrl} alt={`${names[platform]} ${f.page}`} style={{width:'100%',display:'block',border:'1px solid var(--line)'}}/><div className="muted" style={{marginTop:5}}>第 {f.page} 页</div></a>)}</div>}{a&&a.status!=='generating'&&<div style={{marginTop:18,borderTop:'1px solid var(--line)',paddingTop:14}}><strong>修改这套平台排版</strong><textarea style={{minHeight:100,marginTop:8}} value={notes[platform]||''} onChange={e=>setNotes((v:any)=>({...v,[platform]:e.target.value}))} placeholder="例如：第 2 页留白多一点；第 4 页把图片放大；可以增加页数，但不要删字、改字、换图。"/><ImageDropPaste files={files[platform]||[]} onChange={(next)=>setFiles((v:any)=>({...v,[platform]:next}))} max={6} label="排版参考图片" compact/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button className="secondary" disabled={!!busy||!(notes[platform]||'').trim()} onClick={()=>adapt(platform,notes[platform])}>{busy===platform?'修改中…':'修改适配'}</button>{a.status!=='approved'&&a.files?.length>0&&<button disabled={!!busy} onClick={()=>approve(a)}>{busy==='approve:'+platform?'确认中…':`确认${names[platform]}这版`}</button>}</div></div>}</div>})}</div>
{item.publish_state==='ready_to_publish'&&<><div className="card" style={{marginTop:16}}><div className="meta"><span className="pill">素材 Ready</span></div><h2>三端素材已确认</h2><p className="muted">平台适配阶段结束，可以进入发布控制台。</p><a className="button-link" href={`/release/publish?id=${encodeURIComponent(item.content_id)}`}>发布内容 →</a></div><a className="button-link publish-fab" href={`/release/publish?id=${encodeURIComponent(item.content_id)}`}>发布 →</a></>}</>}
