import fs from'node:fs';import path from'node:path';import{execFile,spawn}from'node:child_process';import{promisify}from'node:util';import{beginAdaptation,completeAdaptation,failAdaptation,getHtmlVisualState,getPublishPackage,getReleaseItem}from'../../../../lib/db';import{GUIZANG_ENGINE}from'../../../../lib/guizang-social-card';import{buildGuizangPlatformPages}from'../../../../lib/guizang-layout';import{load}from'cheerio';
export const runtime='nodejs';export const maxDuration=300;const run=promisify(execFile),chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
function refs(pkg:string,x:any[]){const root=path.resolve(process.cwd(),'public','generated',pkg,'assets','uploads'),a:string[]=[];for(const v of Array.isArray(x)?x:[]){const r=String(v?.relPath||v||'');if(!r.startsWith('assets/uploads/'))continue;const p=path.resolve(process.cwd(),'public','generated',pkg,r);if(p.startsWith(root+path.sep)&&fs.existsSync(p))a.push(p)}return a.slice(0,6)}
function htmlText(h:string){return h.replace(/<head\b[\s\S]*?<\/head>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'")}
function publishableHtml(x:string){const $=load(x);$('figcaption').each((_,el)=>{if($(el).text().trim().startsWith('图像来源：'))$(el).remove()});$('.endnote').each((_,el)=>{const t=$(el).text();if(t.includes('SOURCES.md')||t.includes('内部排版预览'))$(el).remove()});return $.html()}
function compact(x:string){return htmlText(publishableHtml(x)).replace(/\s+/g,'')}
function imageSrcs(h:string){return[...h.matchAll(/<img\b[^>]*\bsrc=["']([^"']+)["']/gi)].map(m=>m[1].replace(/&amp;/g,'&'))}
function imageKey(packageId:string,htmlFile:string,src:string){const root=path.join(process.cwd(),'public','generated',packageId);if(src.startsWith('/api/publish/generated-file?')){try{const u=new URL('http://local'+src);return'pkg:'+String(u.searchParams.get('file')||'')}catch{}}if(src.startsWith('/api/publish/cover-file?')){try{const u=new URL('http://local'+src);if(u.searchParams.get('kind')==='logo')return'brand:logo'}catch{}}if(/^https?:\/\//i.test(src))return'url:'+src;const abs=path.resolve(path.dirname(htmlFile),src),rel=path.relative(root,abs).split(path.sep).join('/');return rel.startsWith('..')?'file:'+abs:'pkg:'+rel}
function lockedImages(packageId:string,masterHtml:string){const h=fs.readFileSync(masterHtml,'utf8');return[...new Set(imageSrcs(h).map(src=>imageKey(packageId,masterHtml,src)))].filter(Boolean)}
function validateLocked(packageId:string,pkg:any,masterHtml:string,files:string[],coverVisualPath:string){
  const masterRaw=fs.readFileSync(masterHtml,'utf8'),masterText=compact(masterRaw);let actualRaw=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
  let actualVisible=htmlText(actualRaw).replace(/\b\d{1,2}\s*\/\s*\d{1,2}\b/g,' ');const actualText=actualVisible.replace(/\s+/g,'');
  if(actualText!==masterText)throw Error(`MASTER_TEXT_LOCK_VIOLATION: expected ${masterText.length} chars, got ${actualText.length}`);
  const expected=lockedImages(packageId,masterHtml),allowed=new Set(expected);const coverKey=imageKey(packageId,masterHtml,path.relative(path.dirname(masterHtml),coverVisualPath).split(path.sep).join('/'));allowed.add(coverKey);allowed.add('brand:logo');const actual=new Set<string>();for(const f of files){for(const src of imageSrcs(fs.readFileSync(f,'utf8')))actual.add(imageKey(packageId,f,src))}
  for(const k of expected)if(!actual.has(k))throw Error(`IMAGE_LOCK_VIOLATION: missing ${k}`);if(!actual.has(coverKey))throw Error('IMAGE_LOCK_VIOLATION: shared Minimal Poster cover artwork missing');if(!actual.has('brand:logo'))throw Error('IMAGE_LOCK_VIOLATION: VOX logo missing');for(const k of actual)if(!allowed.has(k))throw Error(`IMAGE_LOCK_VIOLATION: unapproved ${k}`);return{textChars:masterText.length,images:expected}
}

async function assertRenderedImages(masterId:string,html:string){const rel=path.relative(path.join(process.cwd(),'public','generated',masterId),html).split(path.sep).join('/'),url=`http://127.0.0.1:3000/api/publish/generated-file?packageId=${encodeURIComponent(masterId)}&file=${encodeURIComponent(rel)}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('ADAPT_HTML_NOT_LOADABLE');const body=await r.text();for(const src of imageSrcs(body)){if(src.startsWith('data:'))continue;const abs=new URL(src,url).toString(),ir=await fetch(abs,{cache:'no-store'});if(!ir.ok||!String(ir.headers.get('content-type')||'').startsWith('image/'))throw Error('ADAPT_IMAGE_NOT_LOADABLE: '+src)}}
async function recoverExisting(aid:string,masterId:string,dir:string,manifest:string,instruction:string,pkg:any,masterHtml:string,coverVisual:string){
  if(!fs.existsSync(manifest))return null;let m:any;try{m=JSON.parse(fs.readFileSync(manifest,'utf8'))}catch{return null}
  const pages=(Array.isArray(m.pages)?m.pages:[]).map((v:any)=>typeof v==='string'?v:v?.file).filter(Boolean);if(!pages.length||pages.length>24)return null
  const htmlFiles:string[]=[];for(const x of pages){const name=path.basename(String(x)),html=path.join(dir,name);if(!/^page-\d+\.html$/.test(name)||!fs.existsSync(html))return null;htmlFiles.push(html)}
  validateLocked(masterId,pkg,masterHtml,htmlFiles,coverVisual)
  const files:any[]=[];for(let i=0;i<htmlFiles.length;i++){const html=htmlFiles[i],png=html.replace(/\.html$/,'.png');await assertRenderedImages(masterId,html);if(!fs.existsSync(png)){const rel=path.relative(path.join(process.cwd(),'public','generated',masterId),html).split(path.sep).join('/'),url=`http://127.0.0.1:3000/api/publish/generated-file?packageId=${encodeURIComponent(masterId)}&file=${encodeURIComponent(rel)}`;await run(chrome,['--headless=new','--hide-scrollbars','--disable-gpu','--force-device-scale-factor=1','--window-size=1080,1440','--virtual-time-budget=2200',`--screenshot=${png}`,url],{timeout:60000,maxBuffer:2_000_000})}files.push({page:i+1,htmlPath:path.relative(process.cwd(),html).split(path.sep).join('/'),pngPath:path.relative(process.cwd(),png).split(path.sep).join('/')})}
  return completeAdaptation(aid,files,GUIZANG_ENGINE,instruction)
}
export async function POST(req:Request){let aid='';try{
  const x=await req.json(),contentId=String(x.contentId||''),platform=String(x.platform||''),instruction=String(x.instruction||'').trim();
  if(!contentId||!['xiaohongshu','douyin'].includes(platform))return Response.json({ok:false,error:'contentId/platform required'},{status:400});
  if(!x.worker){const now:any=getReleaseItem(contentId),e=now?.adaptations?.find((a:any)=>a.platform===platform),hasRefs=Array.isArray(x.uploadedAssets)&&x.uploadedAssets.length>0;if(e?.status==='generating')return Response.json({ok:true,queued:true,alreadyRunning:true,platform},{status:202});if((e?.status==='ready'||e?.status==='approved')&&!instruction&&!hasRefs)return Response.json({ok:true,alreadyReady:true,platform,adaptation:e});const body=JSON.stringify({...x,worker:true});const p=spawn('/usr/bin/curl',['-sS','-X','POST','http://127.0.0.1:3000/api/release/adapt','-H','content-type: application/json','--data-binary',body],{detached:true,stdio:'ignore'});p.unref();return Response.json({ok:true,queued:true,platform},{status:202})}
  const item:any=getReleaseItem(contentId),master:any=item?.master;if(!item||!master)return Response.json({ok:false,error:'公众号视觉母版不存在'},{status:409});if(!['master_approved','platform_adapting','ready_to_publish'].includes(item.publish_state))return Response.json({ok:false,error:'请先确认公众号视觉母版'},{status:409});
  const ms:any=getHtmlVisualState(master.id),pkg:any=getPublishPackage(master.id);if(!pkg||!ms.selected||ms.selected.status!=='final'||!ms.cover?.cover_png_path||!ms.cover?.visual_asset_path)throw Error('公众号母版不完整');
  const masterHtml=ms.selected.current_file_path,coverVisual=path.resolve(process.cwd(),ms.cover.visual_asset_path),expectedImages=lockedImages(master.id,masterHtml),paragraphs=String(pkg.body||'').split(/\n\s*\n/).map((v:string)=>v.trim()).filter(Boolean);
  const existing=item.adaptations?.find((v:any)=>v.platform===platform),a:any=beginAdaptation(contentId,platform,master.id);aid=a.id;const n=(a.current_revision_no||0)+1,tag=`r${String(n).padStart(2,'0')}`,dir=path.join(process.cwd(),'public','generated',master.id,'adaptations',platform,tag);fs.mkdirSync(dir,{recursive:true});const manifest=path.join(dir,'manifest.json');
  const recovered=existing?.status==='generating'?await recoverExisting(aid,master.id,dir,manifest,instruction,pkg,masterHtml,coverVisual):null;if(recovered)return Response.json({ok:true,adaptation:recovered,recovered:true});
  refs(master.id,x.uploadedAssets); // references remain accepted by the existing API; content/assets stay locked to the confirmed master.
  const built=buildGuizangPlatformPages({packageId:master.id,masterHtml,coverVisualPath:coverVisual,platform,outDir:dir,instruction});
  const htmlFiles=built.files;validateLocked(master.id,pkg,masterHtml,htmlFiles,coverVisual);
  const files:any[]=[];for(let i=0;i<htmlFiles.length;i++){const html=htmlFiles[i],png=html.replace(/\.html$/,'.png');await assertRenderedImages(master.id,html);const rel=path.relative(path.join(process.cwd(),'public','generated',master.id),html).split(path.sep).join('/'),url=`http://127.0.0.1:3000/api/publish/generated-file?packageId=${encodeURIComponent(master.id)}&file=${encodeURIComponent(rel)}`;await run(chrome,['--headless=new','--hide-scrollbars','--disable-gpu','--force-device-scale-factor=1','--window-size=1080,1440','--virtual-time-budget=2200',`--screenshot=${png}`,url],{timeout:60000,maxBuffer:2_000_000});files.push({page:i+1,htmlPath:path.relative(process.cwd(),html).split(path.sep).join('/'),pngPath:path.relative(process.cwd(),png).split(path.sep).join('/')})}
  return Response.json({ok:true,adaptation:completeAdaptation(aid,files,GUIZANG_ENGINE,instruction),lock:{paragraphs:paragraphs.length,images:expectedImages.length,blocks:built.blocks,pages:built.pages,engine:'guizang-social-card-skill'}})
}catch(e:any){if(aid)try{failAdaptation(aid,String(e.message||e))}catch{}return Response.json({ok:false,error:String(e.message||e).slice(0,1400)},{status:500})}}
