'use client';import{useEffect,useRef,useState}from'react';
export default function IngestClient(){const input=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[drag,setDrag]=useState(false),[asset,setAsset]=useState<any>(null),[notes,setNotes]=useState(''),[progress,setProgress]=useState(0),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[status,setStatus]=useState<any>(null);
useEffect(()=>{fetch('/api/ingest/check').then(r=>r.json()).then(x=>setStatus(x.status))},[]);
const pick=(fs:File[])=>{const f=fs.find(x=>x.type.startsWith('video/'));if(f){setFile(f);setAsset(null);setProgress(0)}};
const upload=async()=>{if(!file)return;setBusy('upload');const init=await(await fetch('/api/ingest/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,type:file.type,size:file.size,notes})})).json();if(!init.ok){setMsg(init.error);setBusy('');return}await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',`/api/ingest/upload?id=${encodeURIComponent(init.assetId)}`);x.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};x.onload=()=>x.status<300?resolve():reject(new Error(x.responseText));x.onerror=()=>reject(new Error('上传失败'));x.send(file)});const list=await(await fetch('/api/ingest/init')).json();setAsset(list.items.find((v:any)=>v.id===init.assetId));setMsg('视频已进入 Content OS。成片不会被修改。');setBusy('')};
const ai=async()=>{if(!asset)return;setBusy('ai');const x=await(await fetch('/api/ingest/meta',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({assetId:asset.id,notes})})).json();setMsg(x.ok?'标题与分发文案已生成；预测已冻结到增长飞轮。':x.error);if(x.ok)setAsset(x.asset);setBusy('')};
const pub=async(p:string)=>{setBusy(p);const x=await(await fetch('/api/ingest/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({assetId:asset.id,platform:p})})).json();setMsg(x.ok?`${p==='douyin'?'抖音':'小红书'}发布完成。`:`发布失败：${x.error}`);setBusy('')};
const account=async(action:string,p:string)=>{const x=await(await fetch(`/api/ingest/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({platform:p})})).json();setMsg(action==='login'?'已启动登录窗口。':x.valid?'登录态有效。':`登录态异常：${x.output||x.error}`)};
const m=asset?.meta||{};return <><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">已有内容</span><span className="pill">视频不剪辑</span><span className="pill">小红书 + 抖音</span></div><h1 style={{marginTop:10}}>上传已经做好的视频</h1><p className="muted">这里只接管标题、简介、标签、发布和后续数据复盘。视频画面、声音、剪辑本身不处理。</p></div><div className="card" style={{marginBottom:16}}><div className={`video-drop ${drag?'is-dragging':''}`} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);pick(Array.from(e.dataTransfer.files))}}><input hidden ref={input} type="file" accept="video/*" onChange={e=>pick(Array.from(e.target.files||[]))}/><strong>{file?file.name:'把视频拖到这里，或点击选择视频'}</strong>{file&&<div className="muted" style={{marginTop:6}}>{(file.size/1024/1024).toFixed(1)} MB</div>}</div><textarea style={{minHeight:150,marginTop:12}} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="粘贴视频口述稿、字幕稿，或者简单说明视频讲了什么。系统用它起标题和写发布文案。"/>{file&&!asset&&<><button style={{marginTop:10}} disabled={!!busy} onClick={upload}>{busy==='upload'?'上传中…':'上传成片'}</button>{progress>0&&<div className="progress-track"><div className="progress-bar" style={{width:`${progress}%`}}/></div>}</>}</div>{asset&&<div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">视频 Ready</span><span className="pill">{asset.original_name}</span></div><h2 style={{marginTop:12}}>自动标题与分发</h2><button disabled={!!busy||!notes.trim()} onClick={ai}>{busy==='ai'?'K2.6 正在处理…':m.titles?'重新生成':'生成标题 + 两端文案 + 发布前预测'}</button>{m.titles&&<><p><strong>标题候选</strong></p><div className="file-chips">{m.titles.map((t:string)=><span className="pill" key={t}>{t}</span>)}</div><div className="grid" style={{marginTop:14}}>{['xiaohongshu','douyin'].map(p=><div className="card span-6" key={p}><h2>{p==='xiaohongshu'?'小红书':'抖音'}</h2><p><strong>{m[p]?.title}</strong></p><p style={{whiteSpace:'pre-wrap'}}>{m[p]?.desc}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary" onClick={()=>account('check',p)}>检查登录</button><button className="secondary" onClick={()=>account('login',p)}>刷新登录</button><button disabled={!!busy||status?.dryRun} onClick={()=>pub(p)}>{busy===p?'发布中…':'发布视频'}</button></div>{status?.dryRun&&<p className="muted">当前为测试模式，真实发布按钮已锁定。</p>}</div>)}</div></>}</div>}{msg&&<div className="card">{msg}</div>}</>}
