import fs from'node:fs';import path from'node:path';import{getContent,getHtmlVisualState,getMasterPackage,listAdaptations,setDriveArchiveState}from'./db';
const D='https://www.googleapis.com/drive/v3',U='https://www.googleapis.com/upload/drive/v3',FM='application/vnd.google-apps.folder';
function cfg(){return{clientId:process.env.GOOGLE_DRIVE_CLIENT_ID,clientSecret:process.env.GOOGLE_DRIVE_CLIENT_SECRET,refreshToken:process.env.GOOGLE_DRIVE_REFRESH_TOKEN,accessToken:process.env.GOOGLE_DRIVE_ACCESS_TOKEN,rootFolderId:process.env.GOOGLE_DRIVE_ARCHIVE_FOLDER_ID,rootFolderName:process.env.GOOGLE_DRIVE_ARCHIVE_FOLDER_NAME||'VOX Content OS 归档'}}
export function googleDriveArchiveStatus(){const c=cfg(),ok=!!c.accessToken||!!(c.clientId&&c.clientSecret&&c.refreshToken);return{configured:ok,rootFolderConfigured:!!c.rootFolderId,rootFolderName:c.rootFolderName,missing:ok?[]:['GOOGLE_DRIVE_CLIENT_ID','GOOGLE_DRIVE_CLIENT_SECRET','GOOGLE_DRIVE_REFRESH_TOKEN']}}
async function token(){const c=cfg();if(c.accessToken)return c.accessToken;if(!c.clientId||!c.clientSecret||!c.refreshToken)throw Error('GOOGLE_DRIVE_NOT_CONFIGURED');const b=new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:b}),x:any=await r.json().catch(()=>({}));if(!r.ok||!x.access_token)throw Error(`GOOGLE_DRIVE_TOKEN_FAILED: ${String(x?.error_description||x?.error||r.status).slice(0,240)}`);return String(x.access_token)}
function esc(s:string){return s.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
async function api(t:string,url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{authorization:`Bearer ${t}`,...(init.headers||{})}}),raw=await r.text();let x:any={};try{x=raw?JSON.parse(raw):{}}catch{x={raw}}if(!r.ok)throw Error(`GOOGLE_DRIVE_${r.status}: ${String(x?.error?.message||x?.raw||'request failed').slice(0,400)}`);return x}
async function list(t:string,q:string){const u=new URL(`${D}/files`);u.searchParams.set('q',q);u.searchParams.set('fields','files(id,name,mimeType,webViewLink,parents,appProperties)');u.searchParams.set('spaces','drive');return(await api(t,u.toString())).files||[]}
async function meta(t:string,m:any){return api(t,`${D}/files?fields=id,name,mimeType,webViewLink`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(m)})}
async function folder(t:string,parent:string|undefined,name:string,props?:Record<string,string>){let q=`mimeType='${FM}' and name='${esc(name)}' and trashed=false`;if(parent)q+=` and '${esc(parent)}' in parents`;else q+=` and 'root' in parents`;if(props)for(const[k,v]of Object.entries(props))q+=` and appProperties has { key='${esc(k)}' and value='${esc(v)}' }`;return(await list(t,q))[0]||meta(t,{name,mimeType:FM,...(parent?{parents:[parent]}:{}),...(props?{appProperties:props}:{})})}
async function bytes(t:string,parent:string,name:string,b:Buffer,mime:string){const hit=(await list(t,`name='${esc(name)}' and '${esc(parent)}' in parents and trashed=false`))[0],f=hit||await meta(t,{name,parents:[parent],mimeType:mime});return api(t,`${U}/files/${encodeURIComponent(f.id)}?uploadType=media&fields=id,name,webViewLink,modifiedTime,size`,{method:'PATCH',headers:{'content-type':mime},body:b as any})}
async function text(t:string,p:string,n:string,s:string,m='text/plain; charset=utf-8'){return bytes(t,p,n,Buffer.from(s,'utf8'),m)}
function safe(x:string){return x.replace(/[\\/:*?"<>|\r\n]+/g,' ').replace(/\s+/g,' ').trim().slice(0,70)||'未命名内容'}
function local(fp?:string|null){if(!fp)return null;const a=path.resolve(process.cwd(),fp);return a.startsWith(process.cwd()+path.sep)&&fs.existsSync(a)&&fs.statSync(a).isFile()?a:null}
function mime(fp:string){const e=path.extname(fp).toLowerCase();return e==='.png'?'image/png':e==='.jpg'||e==='.jpeg'?'image/jpeg':e==='.webp'?'image/webp':e==='.html'?'text/html; charset=utf-8':e==='.json'?'application/json; charset=utf-8':'application/octet-stream'}
async function file(t:string,p:string,n:string,fp?:string|null){const a=local(fp);return a?bytes(t,p,n,fs.readFileSync(a),mime(a)):null}
function md(item:any,title:string,caption:string){const source=String(item.source_summary||'').trim();return`# ${title}\n\n> 内容 ID：${item.id}\n> 最后同步：${new Date().toISOString()}\n${source?`> 选题来源：${source.replace(/\n/g,' ')}\n`:''}\n## 朋友圈转发文案\n\n${caption||'（未生成）'}\n\n## 最终正文\n\n${String(item.final_text||'').trim()}\n`}
export async function syncContentToGoogleDrive(contentId:string){const st=googleDriveArchiveStatus();if(!st.configured){setDriveArchiveState(contentId,{status:'not_configured',error:'Google Drive OAuth 尚未配置'});return{ok:false,configured:false,status:'not_configured',missing:st.missing}}try{const t=await token(),item:any=getContent(contentId);if(!item?.final_text)throw Error('FINAL_NOT_FOUND');const master:any=getMasterPackage(contentId),title=safe(master?.title||item.topic_title||'VOX 内容'),c=cfg(),root=c.rootFolderId?{id:c.rootFolderId,name:c.rootFolderName}:await folder(t,undefined,c.rootFolderName),stamp=String(item.updated_at||item.created_at||'').slice(0,10)||new Date().toISOString().slice(0,10),dir=await folder(t,root.id,`${stamp}｜${title}｜${contentId.slice(0,8)}`,{voxContentId:contentId}),caption=String(item.archive?.moments_caption||'').trim();await text(t,dir.id,'文章.md',md(item,title,caption),'text/markdown; charset=utf-8');await text(t,dir.id,'归档信息.json',JSON.stringify({contentId,title,topicTitle:item.topic_title,createdAt:item.created_at,updatedAt:item.updated_at,publishState:item.publish_state,contentState:item.content_state,momentsCaption:caption,sourceSummary:item.source_summary||'',voxAngle:item.vox_angle||'',labels:item.labels||[],observations:item.observations||[]},null,2),'application/json; charset=utf-8');if(master){const wx=await folder(t,dir.id,'公众号'),v:any=getHtmlVisualState(master.id);await file(t,wx.id,'封面.png',v.cover?.cover_png_path);await file(t,wx.id,'正文.html',v.selected?.current_file_path);await file(t,wx.id,'封面底图.png',v.cover?.visual_asset_path);const mf=path.join(process.cwd(),'public','generated',master.id,'wechat-mobile','manifest.json');if(fs.existsSync(mf))try{const m=JSON.parse(fs.readFileSync(mf,'utf8')),lf=await folder(t,wx.id,'手机长图');for(const p of m?.pages||[])await file(t,lf.id,`page-${String(p.page).padStart(2,'0')}.png`,p.file)}catch{}for(const a of listAdaptations(contentId) as any[]){if(!a?.files?.length)continue;const label=a.platform==='xiaohongshu'?'小红书':a.platform==='douyin'?'抖音':safe(a.platform),pf=await folder(t,dir.id,label);for(const f of a.files)await file(t,pf.id,`page-${String(f.page).padStart(2,'0')}.png`,f.pngPath)}}const url=dir.webViewLink||`https://drive.google.com/drive/folders/${dir.id}`;setDriveArchiveState(contentId,{status:'synced',folderId:dir.id,folderUrl:url,error:null});return{ok:true,configured:true,status:'synced',folderId:dir.id,folderUrl:url}}catch(e:any){const error=String(e?.message||e).slice(0,1000);setDriveArchiveState(contentId,{status:'failed',error});return{ok:false,configured:true,status:'failed',error}}}
