import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
const ROOT=path.join(process.cwd(),'data','generated');
const MODEL='gpt-image-2';
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function units(s:string){let n=0;for(const c of s)n+=/[\u2e80-\u9fff\uff00-\uffef]/.test(c)?1:/[A-Z0-9]/.test(c)?.62:.52;return n}
function wrap(t:string,max:number){const o:string[]=[];let l='';for(const c of t.replace(/\s+/g,' ').trim()){if(l&&units(l+c)>max){o.push(l);l=c}else l+=c}if(l)o.push(l);return o}
function text(lines:string[],x:number,y:number,lh:number,fsz:number,w=400,fill='#20201d'){return `<text x="${x}" y="${y}" font-family="PingFang SC,Hiragino Sans GB,Arial,sans-serif" font-size="${fsz}" font-weight="${w}" fill="${fill}">${lines.map((l,i)=>`<tspan x="${x}" dy="${i?lh:0}">${esc(l)}</tspan>`).join('')}</text>`}
async function gptImage(prompt:string,out:string){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY_MISSING');const p=`${prompt}\n\nVOX音乐教室 editorial visual. No readable text, letters, numbers, logos, watermarks, QR codes or brand labels. Use generic unbranded music gear. Leave all typography to layout.`;const r=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model:MODEL,prompt:p,size:'1536x1024',quality:'high',output_format:'png'}),signal:AbortSignal.timeout(240000)});const raw=await r.text();if(!r.ok){let m='';try{m=String(JSON.parse(raw)?.error?.message||'').slice(0,200)}catch{}throw new Error(`OPENAI_IMAGE_${r.status}${m?`: ${m}`:''}`)}const b=JSON.parse(raw)?.data?.[0]?.b64_json;if(!b)throw new Error('OPENAI_IMAGE_NO_DATA');await fs.writeFile(out,Buffer.from(b,'base64'));return MODEL}
async function hero(pkg:any,dir:string){const p=path.join(dir,'hero-gpt-image-2.png');return{path:p,model:await gptImage(pkg.visual_prompt||pkg.title,p)}}
export async function renderWechat(pkg:any){const dir=path.join(ROOT,pkg.id);await fs.rm(dir,{recursive:true,force:true});await fs.mkdir(dir,{recursive:true});const h=await hero(pkg,dir);const W=1080,m=82,cw=W-m*2,title=wrap(pkg.title,15),paras=String(pkg.body||'').split(/\n\s*\n/).map((x:string)=>x.trim()).filter(Boolean),fsz=31,lh=53,max=cw/fsz;let y=930+title.length*76+70;const blocks=paras.map((p:string,i:number)=>({i,lines:wrap(p,max)})),pos:any[]=[];for(const b of blocks){pos.push({...b,y});y+=b.lines.length*lh+56}const H=Math.max(2400,y+180);const svg=`<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg"><rect width="${W}" height="${H}" fill="#f1eee6"/><text x="${m}" y="850" font-family="Arial" font-size="21" letter-spacing="4" fill="#b68a4c">VOX MUSIC CLASSROOM · FIELD NOTES</text>${text(title,m,930,76,60,760,'#191713')}${pos.map(b=>`${b.i?`<line x1="${m}" y1="${b.y-30}" x2="${m+95}" y2="${b.y-30}" stroke="#b68a4c" stroke-width="5"/>`:''}${text(b.lines,m,b.y,lh,fsz,420,'#292722')}`).join('')}<text x="${m}" y="${H-90}" font-family="PingFang SC,Arial" font-size="22" fill="#817b70">VOX 音乐教室 · 武汉光谷</text></svg>`;const hb=await sharp(h.path).resize(W,790,{fit:'cover'}).modulate({brightness:.8,saturation:.86}).toBuffer();const out=path.join(dir,'wechat-long-final.png');await sharp(Buffer.from(svg)).composite([{input:hb,left:0,top:0}]).png().toFile(out);return[{filePath:out,width:W,height:H,kind:'wechat_long_image',model:h.model}]}
export async function renderCards(pkg:any,platform:string){const dir=path.join(ROOT,pkg.id);await fs.rm(dir,{recursive:true,force:true});await fs.mkdir(dir,{recursive:true});const h=await hero(pkg,dir);const W=1080,H=1440,m=78,cw=W-m*2,fsz=34,lh=58,max=cw/fsz;const paras=String(pkg.body||'').split(/\n\s*\n/).map((x:string)=>x.trim()).filter(Boolean),pages:any[][]=[];let cur:any[]=[],count=0;for(const p of paras){const ls=wrap(p,max);if(cur.length&&count+ls.length>17){pages.push(cur);cur=[];count=0}cur.push(ls);count+=ls.length+1}if(cur.length)pages.push(cur);const assets:any[]=[];const hb=await sharp(h.path).resize(W,H,{fit:'cover'}).modulate({brightness:.58,saturation:.86}).toBuffer();const cv=Buffer.from(`<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg"><rect x="62" y="62" width="956" height="1316" rx="34" fill="none" stroke="#d6b26f" stroke-opacity=".48" stroke-width="2"/>${text(wrap(pkg.title,13),88,980,88,70,780,'#f5efe4')}<text x="90" y="1280" font-family="Arial" font-size="22" letter-spacing="4" fill="#d8b475">VOX MUSIC CLASSROOM</text></svg>`);const cover=path.join(dir,'card-01-cover.png');await sharp(hb).composite([{input:cv,left:0,top:0}]).png().toFile(cover);assets.push({filePath:cover,width:W,height:H,kind:'cover',model:h.model});for(let i=0;i<pages.length;i++){let y=160;const body=pages[i].map(ls=>{const x=text(ls,m,y,lh,fsz,420,'#292722');y+=ls.length*lh+54;return x}).join('');const svg=Buffer.from(`<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg"><rect width="${W}" height="${H}" fill="#f1eee6"/><text x="${m}" y="84" font-family="Arial" font-size="20" letter-spacing="3" fill="#9e7843">VOX · ${String(i+1).padStart(2,'0')}</text><line x1="${m}" y1="114" x2="${W-m}" y2="114" stroke="#d6cbbb"/>${body}<text x="${W-m}" y="1370" text-anchor="end" font-family="PingFang SC,Arial" font-size="22" fill="#817b70">${platform==='xiaohongshu'?'小红书图文':'抖音图文'} · VOX 音乐教室</text></svg>`);const out=path.join(dir,`card-${String(i+2).padStart(2,'0')}.png`);await sharp(svg).png().toFile(out);assets.push({filePath:out,width:W,height:H,kind:'content_card',model:'local-layout'})}return assets}
export async function renderPackage(pkg:any){if(pkg.platform==='wechat_long_image')return renderWechat(pkg);if(pkg.platform==='xiaohongshu'||pkg.platform==='douyin')return renderCards(pkg,pkg.platform);throw new Error('UNSUPPORTED_PLATFORM')}
