import { XMLParser } from 'fast-xml-parser';
import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { ResearchItem } from './db';
import { omniseekHealth, omniseekResearch } from './omniseek';

const execFileAsync=promisify(execFile);
const OPENCLI=process.env.OPENCLI_BIN||'/Users/voxrockschool/Projects/_skill_installs/opencli/node_modules/.bin/opencli';
const AGENT_REACH=process.env.AGENT_REACH_BIN||'/Users/voxrockschool/Projects/_skill_installs/agent-reach-venv/bin/agent-reach';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex').slice(0,24);
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));

export async function browserBridgeReady(){try{const{stdout}=await execFileAsync(OPENCLI,['doctor'],{timeout:8000});return stdout.includes('[OK] Connectivity')}catch{return false}}
export async function toolStatus(){let reach:any=null,opencli='unavailable';try{const{stdout}=await execFileAsync(AGENT_REACH,['doctor','--json'],{timeout:15000,maxBuffer:1024*1024});reach=JSON.parse(stdout)}catch{}try{const{stdout}=await execFileAsync(OPENCLI,['doctor'],{timeout:10000});opencli=stdout}catch(e:any){opencli=e?.stdout||e?.message||'failed'}const browserBridge=opencli.includes('[OK] Connectivity');const omni=await omniseekHealth();return{reach,opencli,browserBridge,omniseek:{status:omni?'ok':'off',backend:'OmniSeek 0.2.0 · local'},opencliChannels:{xiaohongshu:{status:browserBridge?'ok':'off',backend:'OpenCLI Browser Bridge',verified:browserBridge},douyin:{status:browserBridge?'ok':'off',backend:'OpenCLI Browser Bridge',verified:browserBridge}}}}

async function rss(url:string,source:string,limit=14):Promise<ResearchItem[]>{const res=await fetch(url,{headers:{'user-agent':'VOX-Content-OS/1.0'},signal:AbortSignal.timeout(12000)});if(!res.ok)throw new Error(`${source} RSS ${res.status}`);const parsed=new XMLParser({ignoreAttributes:false,processEntities:false}).parse(await res.text());const raw=parsed?.rss?.channel?.item||parsed?.feed?.entry||[];const arr=Array.isArray(raw)?raw:[raw];return arr.slice(0,limit).map((x:any)=>{const title=typeof x.title==='object'?x.title['#text']||'':String(x.title||'');const link=typeof x.link==='object'?(x.link['@_href']||x.link['#text']):x.link;const published=x.pubDate||x.published||x.updated||'';const summary=String(x.description||x.summary||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,700);return{id:hash(`${source}|${link||title}`),source,title,url:String(link||''),summary,publishedAt:String(published||'')}}).filter((x:ResearchItem)=>x.title)}
async function opencliJson(args:string[],timeout=30000):Promise<any[]>{let last:any;for(let attempt=0;attempt<2;attempt++){try{const{stdout}=await execFileAsync(OPENCLI,[...args,'-f','json'],{timeout,maxBuffer:4*1024*1024});const data=JSON.parse(stdout);return Array.isArray(data)?data:(data?.items||[])}catch(e){last=e;if(attempt===0)await new Promise(r=>setTimeout(r,900))}}throw last}
async function social(keywords:string[],bridge:boolean){const items:ResearchItem[]=[],errors:string[]=[];if(!bridge)return{items,errors:['OpenCLI Browser Bridge 未连接，跳过小红书/抖音']};for(const q of keywords.slice(0,3)){try{const xs=await opencliJson(['xiaohongshu','search',q,'--limit','8']);for(const x of xs)items.push({id:hash(`xhs|${x.url||x.title}`),source:'小红书',title:String(x.title||''),url:x.url,author:x.author,query:q,publishedAt:x.published_at,engagement:{likes:x.likes,comments:x.comments,collects:x.collects,shares:x.shares,views:x.views}})}catch(e:any){errors.push(`小红书 ${q}: ${e.message}`)}if(q===keywords[0]){try{const ds=await opencliJson(['douyin','search',q,'--limit','10']);for(const x of ds)items.push({id:hash(`douyin|${x.url||x.desc}`),source:'抖音',title:String(x.desc||''),url:x.url,author:x.author,query:q,publishedAt:x.published_at,engagement:{plays:x.plays,likes:x.likes,comments:x.comments,shares:x.shares,collects:x.collects}})}catch{errors.push('抖音本轮搜索暂不可用，已由小红书 / OmniSeek / 行业源补位')}}}try{const hot=await opencliJson(['douyin','hashtag','hot','--limit','15']);for(const x of hot)items.push({id:hash(`douyin-hot|${x.id||x.name}`),source:'抖音热点词',title:String(x.name||''),query:'hot',engagement:{views:x.view_count}})}catch(e:any){errors.push(`抖音热点词: ${e.message}`)}return{items,errors}}

const MUSIC_TERMS=['音乐','乐队','摇滚','朋克','爵士','民谣','流行','演唱会','音乐节','livehouse','现场','唱片','专辑','歌手','乐手','音乐人','吉他','贝斯','鼓手','键盘','钢琴','编曲','混音','录音','乐理','和弦','旋律','节奏','音色','排练','演出','练琴','music','band','rock','punk','jazz','guitar','bass','drum','song','album','concert','festival','producer','mixing'];
const INDUSTRY_TERMS=['音乐行业','唱片公司','唱片工业','厂牌','版权','流媒体','票务','巡演','经纪','独立音乐','音乐市场','音乐平台','音乐人收入','演出市场','演唱会经济','音乐节经济','ai音乐','音乐版权','music industry','record label','copyright','streaming','touring','ticket','royalty'];
const HISTORY_TERMS=['摇滚史','音乐史','历史','经典专辑','经典乐队','传奇乐队','乐队史','亚文化','地下音乐','场景','scene','history','classic album','legendary band'];
const PRACTICE_TERMS=['学音乐','教学','入门','练习','练琴','排练','乐理','和弦','编曲','混音','录音','听感','节奏','groove','怎么弹','怎么唱','how to','guide','lesson','practice'];
const SOCIAL_TERMS=['青年','就业','收入','消费','城市','文化','教育','学校','人工智能','ai','版权','审美','焦虑','女性','性别','代际','经济','社会','政策','劳动','平台'];
const GEAR_REVIEW_TERMS=['效果器评测','效果器','单块','pedal','stompbox','开箱','器材评测','音箱评测','插件评测','参数对比','购买指南','值不值得买','最值得买','gear review','amp review','plugin review'];
const OFFTOPIC_TERMS=['抽卡','内鬼','手游','角色池','皮肤','版本更新','游戏攻略','副本','氪金','替换文件','mod','破解版','网盘','绕过','免费下载','无损资源'];
const termCount=(text:string,terms:string[])=>terms.reduce((n,k)=>n+(text.includes(k)?1:0),0);
function num(v:any){if(typeof v==='number')return Number.isFinite(v)?v:0;const s=String(v??'').trim().toLowerCase().replace(/,/g,'');const m=s.match(/(-?\d+(?:\.\d+)?)\s*([万亿km]?)/i);if(!m)return 0;const base=Number(m[1]);const unit=m[2];const mult=unit==='万'?1e4:unit==='亿'?1e8:unit==='k'?1e3:unit==='m'?1e6:1;return Number.isFinite(base)?base*mult:0}
function engagementInfo(i:ResearchItem){const e:any=i.engagement||{};const likes=num(e.likes),comments=num(e.comments),replies=num(e.replies),shares=num(e.shares),collects=num(e.collects),views=num(e.views),plays=num(e.plays);const raw=likes+comments*4+replies*4+shares*6+collects*2+views/400+plays/400;const has=[likes,comments,replies,shares,collects,views,plays].some(x=>x>0);const s=has?clamp(5.4+Math.log10(raw+1)*1.02,5.4,9.9):5.6;const p:string[]=[];if(likes)p.push(`${Math.round(likes).toLocaleString()}赞`);if(comments)p.push(`${Math.round(comments).toLocaleString()}评`);if(replies)p.push(`${Math.round(replies).toLocaleString()}回复`);if(shares)p.push(`${Math.round(shares).toLocaleString()}分享`);if(views||plays)p.push(`${Math.round(views||plays).toLocaleString()}浏览/播放`);return{score:+s.toFixed(1),summary:p.slice(0,3).join(' · ')}}
function relevantToVox(i:ResearchItem){const text=`${i.title} ${i.summary||''}`.toLowerCase(),title=i.title.toLowerCase();const music=termCount(text,MUSIC_TERMS),industry=termCount(text,INDUSTRY_TERMS),off=termCount(text,OFFTOPIC_TERMS),titleMusic=termCount(title,MUSIC_TERMS)+termCount(title,INDUSTRY_TERMS);if(!music&&!industry)return false;if(/绕过|替换文件|免费下载|破解版|无损资源|录音\[\d{2,3}-\d{2,3}\]/i.test(title))return false;if(i.source==='抖音热点词'&&music<1&&industry<1)return false;if(i.source.includes('百度贴吧')&&off>0&&!/(乐队|摇滚|演唱会|巡演|音乐节|专辑|吉他|贝斯|鼓手|版权|厂牌)/i.test(title))return false;if((i.source.includes('OmniSeek')||i.source==='小红书'||i.source==='抖音')&&titleMusic===0&&!/(歌|曲|唱|乐队|摇滚|音乐|专辑|吉他|贝斯|鼓|演出|巡演|版权|厂牌|livehouse|concert|band|rock)/i.test(title))return false;if(i.title.trim().length<7&&music<2&&industry<1)return false;return true}
function score(i:ResearchItem){let age=21;if(i.publishedAt){const t=Date.parse(i.publishedAt);if(Number.isFinite(t))age=Math.max(0,(Date.now()-t)/86400000)}const freshness=clamp(9.8-Math.log2(age+1)*.72,5,9.8);const text=`${i.title} ${i.summary||''}`.toLowerCase();const music=termCount(text,MUSIC_TERMS),industry=termCount(text,INDUSTRY_TERMS),history=termCount(text,HISTORY_TERMS),practice=termCount(text,PRACTICE_TERMS),social=termCount(text,SOCIAL_TERMS),gear=termCount(text,GEAR_REVIEW_TERMS);const edu=(text.match(/为什么|怎么|教程|教学|入门|解析|原理|技巧|how|why|guide|learn|lesson|\?|？/g)||[]).length;let voxFit=4.7+Math.min(music,5)*.5+Math.min(industry,3)*.68+Math.min(history,2)*.62+Math.min(practice,3)*.28+Math.min(social,2)*.18+Math.min(edu,2)*.2;if(industry)voxFit+=.35;if(history)voxFit+=.35;if(gear)voxFit-=2.3+Math.min(gear-1,2)*.35;if(/开箱|购买指南|值不值得买|评测|review/i.test(text)&&gear)voxFit-=.5;if(i.title.length<12&&music<2&&industry<1)voxFit-=.7;voxFit=clamp(voxFit,3.8,9.9);const eng=engagementInfo(i);const total=freshness*.22+voxFit*.38+eng.score*.40;return{freshness:+freshness.toFixed(1),voxFit:+voxFit.toFixed(1),audible:eng.score,total:+total.toFixed(2),engagementSummary:eng.summary,industry,history,practice,social,gear}}

const DEFAULT_KEYWORDS=['音乐 行业 热点','乐队 摇滚 演出','音乐 社会 热点','AI 音乐 版权'];
function angle(s:ReturnType<typeof score>){if(s.industry)return'从音乐人、乐队、演出现场或普通听众会受影响的地方切入，把行业变化讲成人能感到的变化。';if(s.history)return'围绕一个乐队、一张专辑、一个声音或一段现场史展开，讲清当时发生了什么，以及今天为什么还值得听。';if(s.social)return'抓音乐文化和社会议题的交叉点，避免只追热搜，落到音乐人、听众、学习者或现场。';if(s.practice)return'从听得见、练得到或排练中会遇到的问题切入，不靠器材购买制造内容。';return'从普通听众能听见的具体声音或现象切入，再补音乐知识和背景。'}
function topicType(s:ReturnType<typeof score>){if(s.industry)return'音乐行业 / 热点评论';if(s.history)return'乐队 / 摇滚历史';if(s.practice)return'音乐科普 / 教学';return'音乐文化 / 图文'}
export async function runResearch(keywords=DEFAULT_KEYWORDS){const errors:string[]=[],items:ResearchItem[]=[];const feeds=[['https://www.musicradar.com/rss','MusicRadar'],['https://cdm.link/feed/','Create Digital Music']] as const;const bridge=await browserBridgeReady();const year=new Date().getFullYear();const omniQueries=[`音乐行业 ${year}`,`乐队 摇滚 ${year}`,`演唱会 音乐节 ${year}`,`AI 音乐 版权 ${year}`,'摇滚 历史 乐队',`音乐 社会 文化 ${year}`];const [settled,soc,omni]=await Promise.all([Promise.allSettled(feeds.map(([u,s])=>rss(u,s))),social(keywords,bridge),omniseekResearch(omniQueries)]);settled.forEach(r=>{if(r.status==='fulfilled')items.push(...r.value)});items.push(...soc.items);errors.push(...soc.errors);for(const x of omni.items){x.id=hash(`omniseek|${x.source}|${x.url||x.title}`);items.push(x)}errors.push(...omni.errors);const seen=new Set<string>();const unique=items.filter(i=>i.title&&!seen.has(i.id)&&!!seen.add(i.id));const candidates=unique.filter(relevantToVox);const topics=candidates.map(i=>{const s=score(i);const sourceLabel=`${i.source}${i.author?` · ${i.author}`:''}`;const why=s.engagementSummary?`${sourceLabel}；${s.engagementSummary}，互动信号已纳入综合分。`:`来自 ${sourceLabel} 的材料，按时效与音乐相关度进入候选。`;return{id:`topic-${i.id}`,title:i.title.trim().slice(0,150),column:s.practice?'yueshi':'yueli',whyNow:why,voxAngle:angle(s),source:`${sourceLabel}${i.url?` · ${i.url}`:''}`,sourceUrl:i.url||null,freshness:s.freshness,voxFit:s.voxFit,audible:s.audible,total:s.total,format:topicType(s)}}).filter(t=>t.voxFit>=5.5&&t.total>=5.9).sort((a,b)=>b.total-a.total).slice(0,60);return{items:unique,topics,errors,browserBridge:bridge,omniseek:omni.items.length>0}}
