'use client';
import {useEffect,useMemo,useState} from 'react';
import ImageDropPaste from '../../components/ImageDropPaste';
import {ContentJourney} from '../../components/ContentJourney';

const meta:any={
  xiaohongshu:{name:'小红书图文',desc:'先生成文案与视觉方向。需要实际配图时再进入后续视觉制作。'},
  wechat_long_image:{name:'公众号长图版式',desc:'先确认标题、正文和排版方向，再选择一版继续调整。'},
  douyin:{name:'抖音图文',desc:'先生成文案与视觉方向。需要实际配图时再进入后续视觉制作。'}
};
const order=['wechat_long_image'];
const themeOptions=[
  {key:'vox_zine_editorial_html',label:'暖纸编辑版',note:'暖纸、明朝体、克制的长文版式'},
  {key:'open_design_editorial',label:'长文杂志版',note:'有节奏的长文阅读版式'},
  {key:'source_han_serif_clean',label:'思源宋体版',note:'干净、安静、适合长文阅读'}
];
const visualJobStatus:any={generating:'生成中',succeeded:'已成功',failed:'失败'};

async function uploadImages(packageId:string,files:File[]){if(!files.length)return[];const f=new FormData();f.append('packageId',packageId);files.forEach(x=>f.append('files',x));const r=await(await fetch('/api/publish/upload',{method:'POST',body:f})).json();if(!r.ok)throw new Error(r.error||'图片上传失败');return r.files||[]}
async function jsonWithTimeout(url:string,init:RequestInit={},timeoutMs=15000){const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...init,signal:controller.signal}),json=await response.json();return{response,json}}finally{window.clearTimeout(timer)}}

function ArchiveCard({item,onChanged}:{item:any;onChanged:()=>Promise<void>}){const[busy,setBusy]=useState(false),[note,setNote]=useState('');const a=item.archive||{};const sync=async()=>{setBusy(true);const r=await fetch('/api/archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.content_id})}),x=await r.json();setNote(x.ok?'归档已同步。':x.drive?.status==='not_configured'?'还没有设置云端归档，朋友圈文案已保存在本地。':`归档同步失败：${x.error||x.drive?.error||'unknown'}`);setBusy(false);await onChanged()};return <div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">朋友圈一句话</span><span className="pill">归档 {a.drive_status==='synced'?'已完成':a.drive_status==='failed'?'同步失败':'待设置'}</span></div><h2 style={{marginTop:10}}>转发朋友圈</h2><p style={{fontSize:17,lineHeight:1.7}}>{a.moments_caption||'保存定稿后会自动生成一条朋友圈转发文案。'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{a.moments_caption&&<button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(a.moments_caption);setNote('朋友圈文案已复制。')}catch{setNote('复制失败，请手动复制。')}}}>复制朋友圈文案</button>}<button className="secondary" disabled={busy} onClick={sync}>{busy?'同步中…':'同步归档'}</button>{a.drive_folder_url&&<a className="button-link secondary" href={a.drive_folder_url} target="_blank">打开归档文件夹 ↗</a>}</div>{(note||a.drive_last_error)&&<p className="muted" style={{marginBottom:0}}>{note||a.drive_last_error}</p>}</div>}

function CoverPlan({cover,onChanged}:{cover:any,onChanged:()=>Promise<void>}){
  const[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[instruction,setInstruction]=useState(''),[files,setFiles]=useState<File[]>([]);
  const status:any={not_started:'待生成',dormant:'待生成',generating:'生成中',ready:'已生成',failed:'生成失败'};
  const make=async()=>{if(!cover?.package_id)return;setBusy(true);setMsg('正在创建封面生成任务…');try{const{response,json}=await jsonWithTimeout('/api/publish/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:cover.package_id})});if(!response.ok||!json.ok)throw Error(json.error||'封面任务创建失败');const id=json.generationId||json.cover?.generation_id||'已有任务';setMsg(`${json.alreadyRunning?'封面生成任务已在执行':'封面生成任务已创建'}（${id}）。页面会自动回读成功、失败或超时状态。`)}catch(e:any){setMsg(e?.name==='AbortError'?'封面任务请求超时；请刷新查看持久状态，完成后可重试。':`生成失败：${e?.message||e}`)}setBusy(false);await onChanged()};
  const revise=async()=>{setBusy(true);setMsg('正在根据修改意见调整封面…');try{const refs=await uploadImages(cover.package_id,files),x=await(await fetch('/api/publish/cover/workflow',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packageId:cover.package_id,instruction,uploadedAssets:refs})})).json();if(!x.ok)throw new Error(x.error);setMsg(`封面第 ${x.revisionNo} 版已生成，上一版已保留。`);setInstruction('');setFiles([])}catch(e:any){setMsg('修改失败：'+e.message)}setBusy(false);await onChanged()};
  const generating=cover?.status==='generating';
  return <div className="card" style={{marginTop:22,padding:18,background:'var(--bg)'}}><div className="meta"><span className="pill">公众号封面</span><span className="pill">{status[cover?.status]||'待生成'}</span>{cover?.generation_id&&generating&&<span className="pill">任务 {cover.generation_id}</span>}{cover?.current_revision_no>0&&<span className="pill">第 {cover.current_revision_no} 版</span>}</div><h3 style={{marginTop:12}}>统一封面</h3><p className="muted">封面会和公众号正文保持同一套版式；这里只调整尺寸、标题和布局，不改正文内容。</p>{cover?.pngUrl&&<img src={cover.pngUrl} alt="公众号封面" style={{width:'100%',marginTop:14,border:'1px solid var(--line)'}}/>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button disabled={busy||generating} onClick={make}>{busy?'处理中…':generating?'封面生成中…':cover?.status==='failed'?'重试生成封面':cover?.pngUrl?'重新生成封面':'生成封面'}</button>{cover?.pngUrl&&<a className="button-link secondary" href={cover.pngUrl} target="_blank">打开当前封面 ↗</a>}</div>{cover?.error_text&&<p className="muted">上次任务失败：{cover.error_text}。可以重试。</p>}{cover?.pngUrl&&<div style={{marginTop:18,borderTop:'1px solid var(--line)',paddingTop:16}}><strong>修改当前封面</strong><textarea style={{minHeight:100,marginTop:8}} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：标题小一点，主体往左移，保留底图；也可以上传参考图。"/><ImageDropPaste files={files} onChange={setFiles} max={6} label="参考图片" compact/><div><button style={{marginTop:10}} disabled={busy||!instruction.trim()} onClick={revise}>修改封面</button></div></div>}{cover?.revisions?.length>0&&<div style={{marginTop:18}}><strong>封面修改记录</strong>{cover.revisions.map((r:any)=><div key={r.id} style={{padding:'8px 0',borderBottom:'1px solid var(--line)'}}><span className="pill">第 {r.revision_no} 版</span> <span className="muted">{r.edit_instruction}</span> <a href={r.pngUrl} target="_blank">查看</a></div>)}</div>}{msg&&<p className="muted">{msg}</p>}</div>
}

function HtmlVariants({p}:{p:any}){
  const[state,setState]=useState<any>({variants:[],selected:null,cover:null,generationJobs:[]}),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[instruction,setInstruction]=useState(''),[files,setFiles]=useState<File[]>([]);
  const load=async()=>{const x=await(await fetch(`/api/publish/html?packageId=${encodeURIComponent(p.id)}`,{cache:'no-store'})).json();if(x.ok)setState(x)};
  useEffect(()=>{load()},[p.id]);
  const hasRunning=Boolean(state.cover?.status==='generating'||state.generationJobs?.some((j:any)=>j.status==='generating'));
  useEffect(()=>{if(!hasRunning)return;const timer=window.setInterval(()=>{load()},2000);return()=>window.clearInterval(timer)},[p.id,hasRunning]);
  const generate=async(theme:string)=>{setBusy(`gen:${theme}`);setMsg('正在创建版式任务…');try{const{response,json}=await jsonWithTimeout('/api/publish/html',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packageId:p.id,theme})});if(!response.ok||!json.ok)throw Error(json.error||'版式任务创建失败');setMsg(`${json.alreadyRunning?'版式任务已在执行':'版式任务已创建'}（${json.job?.id||'已有任务'}）。页面会自动回读成功、失败或超时状态。`)}catch(e:any){setMsg(e?.name==='AbortError'?'版式任务请求超时；请刷新查看持久状态，完成后可重试。':`生成失败：${e?.message||e}`)}setBusy('');await load()};
  const action=async(payload:any,label:string)=>{setBusy(payload.action);setMsg(label);const x=await(await fetch('/api/publish/html/workflow',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})).json();setMsg(x.ok?(payload.action==='select'?'已选为当前方案，可以继续修改。':payload.action==='revise'?'修改版已生成，原版和记录都保留。':'这一版已确认。'):`失败：${x.error}`);if(x.ok&&payload.action==='revise')setInstruction('');setBusy('');await load()};
  const revise=async()=>{if(!state.selected)return;setBusy('revise');setMsg(files.length?'正在上传参考图并调整版式…':'正在根据修改意见调整版式…');try{const refs=await uploadImages(p.id,files),x=await(await fetch('/api/publish/html/workflow',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'revise',variantId:state.selected.id,instruction,uploadedAssets:refs})})).json();if(!x.ok)throw new Error(x.error);setMsg('修改版已生成，上传图片已作为本轮参考。');setInstruction('');setFiles([])}catch(e:any){setMsg('修改失败：'+e.message)}setBusy('');await load()};
  const confirmMaster=async()=>{if(!state.selected)return;setBusy('master');setMsg('正在确认公众号统一版式…');const x=await(await fetch('/api/publish/master/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packageId:p.id})})).json();if(x.ok){setMsg('公众号统一版式已确认，进入平台排版。');window.location.href=x.nextUrl;return}setMsg('确认失败：'+x.error);setBusy('')};
  const sel=state.selected;
  return <div style={{marginTop:22,borderTop:'1px solid var(--line)',paddingTop:18}}><h3>公众号长图版式</h3><p className="muted">先看不同方案。觉得某一版接近了，就选它继续修改；之后每次都在当前方案上迭代。</p><div className="grid">{themeOptions.map(t=>{const v=state.variants?.find((x:any)=>x.theme_key===t.key),job=state.generationJobs?.find((x:any)=>x.theme_key===t.key),selected=v&&(v.status==='selected'||v.status==='final'),generating=job?.status==='generating';return <div className="card span-4" key={t.key} style={{padding:14,outline:selected?'2px solid currentColor':'none'}}><div className="meta">{selected&&<span className="pill">{v.status==='final'?'已确认':'当前方案'}</span>}</div><strong>{t.label}</strong><p className="muted" style={{minHeight:44}}>{t.note}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy||selected||generating} onClick={()=>generate(t.key)}>{busy===`gen:${t.key}`?'任务创建中…':generating?'生成中…':job?.status==='failed'?'重试生成':v?'重新生成':'生成这个版本'}</button>{v&&<a className="button-link secondary" href={v.url} target="_blank">打开预览 ↗</a>}{v&&!selected&&<button className="secondary" disabled={!!busy||generating} onClick={()=>action({action:'select',packageId:p.id,theme:t.key},'正在选择这个方案…')}>选这版继续修改</button>}</div>{job&&<p className="muted" style={{wordBreak:'break-word',marginBottom:0}}>任务 {job.id} · {visualJobStatus[job.status]||job.status}{job.error_text?`：${job.error_text}`:''}</p>}</div>})}</div>
  {sel&&<div className="card" style={{marginTop:18,padding:18}}><div className="meta"><span className="pill">当前方案：{sel.label}</span><span className="pill">修改 {sel.current_revision_no||0} 次</span>{sel.status==='final'&&<span className="pill">已确认</span>}</div><h3 style={{marginTop:12}}>继续修改这一版</h3><iframe src={sel.url} title="当前公众号正文预览" style={{width:'100%',height:680,border:'1px solid var(--line)',borderRadius:10,background:'#fff'}}/><div style={{marginTop:14}}><strong>修改意见</strong><textarea style={{minHeight:120,marginTop:8}} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：把我上传的图片放到第二段，宽度铺满正文；图注小一点；不要改文章正文。"/><ImageDropPaste files={files} onChange={setFiles} max={6} label="本轮参考图片" compact/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button disabled={!!busy||!instruction.trim()} onClick={revise}>{busy==='revise'?'修改生成中…':'修改这一版'}</button><button disabled={!!busy||state.cover?.status!=='ready'} onClick={confirmMaster}>{busy==='master'?'正在进入平台排版…':'确认版式 → 进入平台排版'}</button><a className="button-link secondary" href={sel.url} target="_blank">全屏查看 ↗</a></div>{state.cover?.status!=='ready'&&<p className="muted">确认版式前，需要先把下方公众号封面生成好。</p>}</div>{sel.revisions?.length>0&&<div style={{marginTop:18}}><strong>修改记录</strong>{sel.revisions.map((r:any)=><div key={r.id} style={{padding:'9px 0',borderBottom:'1px solid var(--line)'}}><span className="pill">第 {r.revision_no} 版{r.is_final?' · 已确认':''}</span> <span className="muted">{r.edit_instruction}</span> <a href={r.url} target="_blank">查看</a></div>)}</div>}</div>}
  {msg&&<p className="muted">{msg}</p>}<CoverPlan cover={state.cover} onChanged={load}/></div>
}

function PackageEditor({p,onChanged}:{p:any;onChanged:()=>Promise<void>}){const[title,setTitle]=useState(p.title),[body,setBody]=useState(p.body),[visual,setVisual]=useState(p.visual_prompt||''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{setTitle(p.title);setBody(p.body);setVisual(p.visual_prompt||'')},[p.id,p.updated_at]);const save=async()=>{setBusy(true);const x=await(await fetch('/api/publish/package',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:p.id,title,body,visualPrompt:visual})})).json();setMsg(x.ok?'修改已保存。需要重新做版式时，直接选择对应方案即可。':`失败：${x.error}`);setBusy(false);await onChanged()};const approve=async()=>{setBusy(true);const x=await(await fetch('/api/publish/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:p.id})})).json();setMsg(x.ok?'内容和排版方向已确认。'+(p.platform==='wechat_long_image'?'下面可以开始制作长图版式。':'实际图片制作可以稍后进行。'):`失败：${x.error}`);setBusy(false);await onChanged()};return <div><div className="meta"><span className="pill">公众号内容 {p.status==='publish_approved'||p.status==='master_approved'?'已确认':'待确认'}</span>{p.platform==='wechat_long_image'&&<span className="pill">长图版式</span>}</div><p><strong>公众号标题</strong></p><textarea style={{minHeight:90}} value={title} onChange={e=>setTitle(e.target.value)}/><p><strong>公众号正文</strong></p><textarea value={body} onChange={e=>setBody(e.target.value)}/><p><strong>排版方向</strong></p><textarea style={{minHeight:140}} value={visual} onChange={e=>setVisual(e.target.value)}/><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><button className="secondary" disabled={busy} onClick={save}>保存修改</button>{p.status!=='publish_approved'&&p.status!=='master_approved'&&<button disabled={busy} onClick={approve}>{busy?'处理中…':'确认内容并进入视觉制作'}</button>}</div>{msg&&<p className="muted">{msg}</p>}{p.platform==='wechat_long_image'&&(p.status==='publish_approved'||p.status==='master_approved')&&<HtmlVariants p={p}/>}</div>}

function PublishHub(){return <><div className="page-intro"><div><h1>发布</h1><p className="muted">选择你要发布的内容来源。两条路径彼此独立，进入后会看到对应的下一步。</p></div><span className="badge">测试模式，不会写入外部平台</span></div><div className="grid publish-hub"><section className="card span-6 publish-path"><div className="action-letter">A</div><h2>发布 Sinote 内已经做好的内容</h2><p className="muted">从内容库选择一条已经完成或正在制作的内容，继续做视觉、排版和发布准备。</p><a className="button-link" href="/content">从内容库选择 →</a></section><section className="card span-6 publish-path"><div className="action-letter">B</div><h2>上传并发布外部已经做好的成品</h2><p className="muted">上传已经完成的图片或视频，填写标题和正文，进入单独的成品发布流程。</p><a className="button-link" href="/quick-publish">上传成品 →</a></section></div></>}

export default function PublishClient(){const[data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState('');const id=typeof window!=='undefined'?new URLSearchParams(location.search).get('id'):null;const load=async()=>{if(!id){setLoading(false);return}setLoading(true);try{const x=await(await fetch(`/api/publish?id=${encodeURIComponent(id)}`,{cache:'no-store'})).json();setData(x.items||[])}catch(e:any){setMsg(e?.message||'读取失败')}finally{setLoading(false)}};useEffect(()=>{load()},[id]);const item=data[0];const byPlatform=useMemo(()=>new Map((item?.packages||[]).map((p:any)=>[p.platform,p])),[item]);const generate=async(platform:string)=>{if(!item)return;setBusy(platform);setMsg(`正在基于当前定稿生成${meta[platform]?.name||platform}方案…`);const x=await(await fetch('/api/publish/package',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.content_id,platforms:[platform]})})).json();setMsg(x.ok?'方案已生成。先检查内容和排版方向，再确认。':`生成失败：${x.error||x.errors?.join('；')}`);setBusy(null);await load()};if(!id)return <PublishHub/>;if(loading)return <div className="card"><h2>正在读取内容</h2><p className="muted">请稍候，正在读取这条内容。</p></div>;if(!item)return <div className="card"><h2>这条内容还不能进入视觉</h2><p className="muted">请先完成观点、草稿、选稿和定稿，完成后再来制作发布素材。</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="button-link" href={`/editor?id=${encodeURIComponent(id)}#final`}>回到定稿</a><a className="button-link secondary" href={`/content/${encodeURIComponent(id)}`}>查看内容详情</a></div></div>;const lead=String(item.final_text||'').trim().split(/\n|。|！|？/)[0].slice(0,70);return <><ContentJourney contentId={item.content_id} current="visual" doneSteps={['viewpoint','draft','choose','final']}/><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">定稿已确认</span><span className="pill">视觉制作</span></div><h1 style={{fontSize:28,marginTop:10}}>制作发布素材</h1><h2 style={{marginTop:12}}>{lead}{lead.length>=70?'…':''}</h2><p className="muted">把这条定稿做成公众号长图版式和统一封面；确认后，会沿着同一条内容进度进入平台排版和发布。</p><details><summary className="muted" style={{cursor:'pointer'}}>查看当前定稿</summary><div style={{whiteSpace:'pre-wrap',lineHeight:1.8,marginTop:12}}>{item.final_text}</div></details></div><ArchiveCard item={item} onChanged={load}/>{msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}<div className="grid">{order.map(platform=>{const p:any=byPlatform.get(platform);return <div className="card span-12" key={platform}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><h2>{meta[platform].name}</h2><p className="muted">{meta[platform].desc}</p></div><button disabled={!!busy} onClick={()=>generate(platform)}>{busy===platform?'生成中…':p?'重新生成方案':'开始制作'}</button></div>{p?<PackageEditor p={p} onChanged={load}/>:<div className="muted" style={{padding:'22px 0'}}>还没有生成这一平台方案。</div>}</div>})}</div></>}
