'use client';
import {useEffect,useMemo,useState} from 'react';
import ImageDropPaste from '../../components/ImageDropPaste';
const meta:any={
  xiaohongshu:{name:'小红书图文',desc:'先生成文案与视觉方向。需要实际配图时再进入后续视觉制作。'},
  wechat_long_image:{name:'公众号 HTML 排版',desc:'批准文案后，用 Codex + Open Design / VOX Editorial 生成长文 HTML；选中一版后可持续 Revision。封面统一走独立 GC Skill，当前不生图。'},
  douyin:{name:'抖音图文',desc:'先生成文案与视觉方向。需要实际配图时再进入后续视觉制作。'}
};
const order=['wechat_long_image'];
const themeOptions=[
  {key:'vox_zine_editorial_html',label:'VOX Zine Editorial（HTML）',note:'暖纸、明朝体、zine 正文版式；不是 GC 生图 Skill'},
  {key:'open_design_editorial',label:'Open Design Editorial',note:'动态长文杂志版式'},
  {key:'source_han_serif_clean',label:'Source Han Serif Clean',note:'思源宋体体系，干净克制'}
];
async function uploadImages(packageId:string,files:File[]){if(!files.length)return[];const f=new FormData();f.append('packageId',packageId);files.forEach(x=>f.append('files',x));const r=await(await fetch('/api/publish/upload',{method:'POST',body:f})).json();if(!r.ok)throw new Error(r.error||'图片上传失败');return r.files||[]}
function ArchiveCard({item,onChanged}:{item:any,onChanged:()=>Promise<void>}){const[busy,setBusy]=useState(false),[note,setNote]=useState('');const a=item.archive||{};const sync=async()=>{setBusy(true);const r=await fetch('/api/archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.content_id})}),x=await r.json();setNote(x.ok?'Google Drive 已同步。':x.drive?.status==='not_configured'?'Google Drive 还没有配置 OAuth，朋友圈文案已保存在本地归档。':`Drive 同步失败：${x.error||x.drive?.error||'unknown'}`);setBusy(false);await onChanged()};return <div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">朋友圈一句话</span><span className="pill">Drive {a.drive_status==='synced'?'已归档':a.drive_status==='failed'?'同步失败':'待配置'}</span></div><h2 style={{marginTop:10}}>转发朋友圈</h2><p style={{fontSize:17,lineHeight:1.7}}>{a.moments_caption||'保存 Final 后会自动生成一条朋友圈转发文案。'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{a.moments_caption&&<button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(a.moments_caption);setNote('朋友圈文案已复制。')}catch{setNote('复制失败，请手动复制。')}}}>复制朋友圈文案</button>}<button className="secondary" disabled={busy} onClick={sync}>{busy?'同步中…':'同步 Google Drive'}</button>{a.drive_folder_url&&<a className="button-link secondary" href={a.drive_folder_url} target="_blank">打开归档文件夹 ↗</a>}</div>{(note||a.drive_last_error)&&<p className="muted" style={{marginBottom:0}}>{note||a.drive_last_error}</p>}</div>}
function CoverPlan({cover,onChanged}:{cover:any,onChanged:()=>Promise<void>}){const[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[instruction,setInstruction]=useState(''),[files,setFiles]=useState<File[]>([]);const status:any={not_started:'待生成',dormant:'待生成',generating:'生成中',ready:'已生成',failed:'生成失败'};const make=async()=>{setBusy(true);const x=await(await fetch('/api/publish/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:cover.package_id})})).json();setMsg(x.ok?'新的封面 Base 已生成。':'生成失败：'+x.error);setBusy(false);await onChanged()};const revise=async()=>{setBusy(true);setMsg('Codex 正在基于当前封面修改…');try{const refs=await uploadImages(cover.package_id,files),x=await(await fetch('/api/publish/cover/workflow',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packageId:cover.package_id,instruction,uploadedAssets:refs})})).json();if(!x.ok)throw new Error(x.error);setMsg(`封面 R${x.revisionNo} 已生成，上一版已保留。`);setInstruction('');setFiles([])}catch(e:any){setMsg('修改失败：'+e.message)}setBusy(false);await onChanged()};return <div className="card" style={{marginTop:22,padding:18,background:'var(--bg)'}}><div className="meta"><span className="pill">公众号统一封面</span><span className="pill">Minimal Zine Poster v0.1</span><span className="pill">{status[cover?.status]||'待生成'}</span>{cover?.current_revision_no>0&&<span className="pill">R{cover.current_revision_no}</span>}</div><h3 style={{marginTop:12}}>Minimal Poster 封面</h3><p className="muted">底图统一由 Minimal Zine Poster v0.1 Standard Mode 生成；公众号横版只做标题、Logo 与底图的尺寸适配。布局修改不重画底图。</p>{cover?.pngUrl&&<img src={cover.pngUrl} alt="公众号封面" style={{width:'100%',marginTop:14,border:'1px solid var(--line)'}}/>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button disabled={busy} onClick={make}>{busy?'处理中…':cover?.pngUrl?'重新生成全新 Base':'生成封面 Base'}</button>{cover?.pngUrl&&<a className="button-link secondary" href={cover.pngUrl} target="_blank">打开当前封面 ↗</a>}</div>{cover?.pngUrl&&<div style={{marginTop:18,borderTop:'1px solid var(--line)',paddingTop:16}}><strong>修改当前封面</strong><textarea style={{minHeight:100,marginTop:8}} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：标题小一点，主体往左移，保留底图；也可以上传参考图。"/><ImageDropPaste files={files} onChange={setFiles} max={6} label="参考图片" compact/><div><button style={{marginTop:10}} disabled={busy||!instruction.trim()} onClick={revise}>让 Codex 修改这个封面</button></div></div>}{cover?.revisions?.length>0&&<div style={{marginTop:18}}><strong>封面 Revision 历史</strong>{cover.revisions.map((r:any)=><div key={r.id} style={{padding:'8px 0',borderBottom:'1px solid var(--line)'}}><span className="pill">R{r.revision_no}</span> <span className="muted">{r.edit_instruction}</span> <a href={r.pngUrl} target="_blank">查看</a></div>)}</div>}{msg&&<p className="muted">{msg}</p>}</div>}
function HtmlVariants({p}:{p:any}){
  const[state,setState]=useState<any>({variants:[],selected:null,cover:null}),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[instruction,setInstruction]=useState(''),[files,setFiles]=useState<File[]>([]);
  const load=async()=>{const x=await(await fetch(`/api/publish/html?packageId=${encodeURIComponent(p.id)}`,{cache:'no-store'})).json();if(x.ok)setState(x)};
  useEffect(()=>{load()},[p.id]);
  const generate=async(theme:string)=>{setBusy(`gen:${theme}`);setMsg('Codex 正在生成这个 HTML 视觉版本…');const x=await(await fetch('/api/publish/html',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packageId:p.id,theme})})).json();setMsg(x.ok?'视觉版本已生成。可以预览后选择一个继续修改。':`生成失败：${x.error}`);setBusy('');await load()};
  const action=async(payload:any,label:string)=>{setBusy(payload.action);setMsg(label);const x=await(await fetch('/api/publish/html/workflow',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})).json();setMsg(x.ok?(payload.action==='select'?'已锁定这版作为 Base，可以在下面继续改。':payload.action==='revise'?'Revision 已生成，原版和历史修改都保留。':'这一版已最终确认。'):`失败：${x.error}`);if(x.ok&&payload.action==='revise')setInstruction('');setBusy('');await load()};
  const revise=async()=>{if(!state.selected)return;setBusy('revise');setMsg(files.length?'正在上传参考图并交给 Codex…':'Codex 正在基于当前版做增量修改…');try{const refs=await uploadImages(p.id,files);const x=await(await fetch('/api/publish/html/workflow',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'revise',variantId:state.selected.id,instruction,uploadedAssets:refs})})).json();if(!x.ok)throw new Error(x.error);setMsg('Revision 已生成，上传图片已作为本轮视觉输入。');setInstruction('');setFiles([])}catch(e:any){setMsg('修改失败：'+e.message)}setBusy('');await load()};
  const confirmMaster=async()=>{if(!state.selected)return;setBusy('master');setMsg('正在确认公众号视觉母版…');const x=await(await fetch('/api/publish/master/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packageId:p.id})})).json();if(x.ok){setMsg('公众号视觉母版已锁定，进入平台适配。');window.location.href=x.nextUrl;return}setMsg('确认失败：'+x.error);setBusy('')};
  const sel=state.selected;
  return <div style={{marginTop:22,borderTop:'1px solid var(--line)',paddingTop:18}}><h3>公众号 HTML 视觉版本</h3><p className="muted">先看不同方案。觉得某一版接近了，就点“选这版继续修改”；之后不再从零重做，而是只在这一版上迭代。</p><div className="grid">{themeOptions.map(t=>{const v=state.variants?.find((x:any)=>x.theme_key===t.key);const selected=v&&(v.status==='selected'||v.status==='final');return <div className="card span-4" key={t.key} style={{padding:14,outline:selected?'2px solid currentColor':'none'}}><div className="meta">{selected&&<span className="pill">{v.status==='final'?'最终版':'已选 Base'}</span>}</div><strong>{t.label}</strong><p className="muted" style={{minHeight:44}}>{t.note}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy||selected} onClick={()=>generate(t.key)}>{busy===`gen:${t.key}`?'Codex 生成中…':v?'重新生成 Base':'生成这个版本'}</button>{v&&<a className="button-link secondary" href={v.url} target="_blank">打开预览 ↗</a>}{v&&!selected&&<button className="secondary" disabled={!!busy} onClick={()=>action({action:'select',packageId:p.id,theme:t.key},'正在锁定这个 Base…')}>选这版继续修改</button>}</div></div>})}</div>
  {sel&&<div className="card" style={{marginTop:18,padding:18}}><div className="meta"><span className="pill">当前 Base：{sel.label}</span><span className="pill">Revision {sel.current_revision_no||0}</span>{sel.status==='final'&&<span className="pill">最终确认</span>}</div><h3 style={{marginTop:12}}>继续修改这一版</h3><iframe src={sel.url} title="当前公众号 HTML 预览" style={{width:'100%',height:680,border:'1px solid var(--line)',borderRadius:10,background:'#fff'}}/><div style={{marginTop:14}}><strong>修改意见</strong><textarea style={{minHeight:120,marginTop:8}} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：把我上传的图片放到第二段，宽度铺满正文；图注小一点；不要改文章正文。"/><ImageDropPaste files={files} onChange={setFiles} max={6} label="本轮参考图片" compact/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button disabled={!!busy||!instruction.trim()} onClick={revise}>{busy==='revise'?'Revision 生成中…':'让 Codex 修改这一版'}</button><button disabled={!!busy||state.cover?.status!=='ready'} onClick={confirmMaster}>{busy==='master'?'正在进入平台适配…':'确认公众号母版 → 平台适配'}</button><a className="button-link secondary" href={sel.url} target="_blank">全屏查看 ↗</a></div>{state.cover?.status!=='ready'&&<p className="muted">确认母版前，需要先把下方公众号封面生成好。</p>}</div>{sel.revisions?.length>0&&<div style={{marginTop:18}}><strong>Revision 历史</strong>{sel.revisions.map((r:any)=><div key={r.id} style={{padding:'9px 0',borderBottom:'1px solid var(--line)'}}><span className="pill">R{r.revision_no}{r.is_final?' · Final':''}</span> <span className="muted">{r.edit_instruction}</span> <a href={r.url} target="_blank">查看</a></div>)}</div>}</div>}
  {msg&&<p className="muted">{msg}</p>}<CoverPlan cover={state.cover} onChanged={load}/></div>
}
function PackageEditor({p,onChanged}:{p:any,onChanged:()=>Promise<void>}){
  const[title,setTitle]=useState(p.title),[body,setBody]=useState(p.body),[visual,setVisual]=useState(p.visual_prompt||''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{setTitle(p.title);setBody(p.body);setVisual(p.visual_prompt||'')},[p.id,p.updated_at]);
  const save=async()=>{setBusy(true);const x=await(await fetch('/api/publish/package',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:p.id,title,body,visualPrompt:visual})})).json();setMsg(x.ok?'修改已保存。公众号 HTML 需要重新生成时，直接选对应视觉版本即可。':`失败：${x.error}`);setBusy(false);await onChanged()};
  const approve=async()=>{setBusy(true);const x=await(await fetch('/api/publish/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:p.id})})).json();setMsg(x.ok?'文案与视觉方向已批准。'+(p.platform==='wechat_long_image'?'下面可以用 Codex 生成 HTML 排版。':'实际图片制作暂缓，后续需要时再做。'):`失败：${x.error}`);setBusy(false);await onChanged()};
  return <div><div className="meta"><span className="pill">公众号文案 {p.status==='publish_approved'||p.status==='master_approved'?'已确认':'待确认'}</span><span className="pill">文案 {p.model_name}</span>{p.platform==='wechat_long_image'&&<><span className="pill">排版 Codex</span><span className="pill">图片优先真实素材</span></>}</div><p><strong>平台标题</strong></p><textarea style={{minHeight:90}} value={title} onChange={e=>setTitle(e.target.value)}/><p><strong>平台正文 / 长图文案</strong></p><textarea value={body} onChange={e=>setBody(e.target.value)}/><p><strong>视觉与排版方向</strong></p><textarea style={{minHeight:140}} value={visual} onChange={e=>setVisual(e.target.value)}/><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><button className="secondary" disabled={busy} onClick={save}>保存修改</button>{p.status!=='publish_approved'&&p.status!=='master_approved'&&<button disabled={busy} onClick={approve}>{busy?'处理中…':'确认文案并进入视觉制作'}</button>}</div>{msg&&<p className="muted">{msg}</p>}{p.platform==='wechat_long_image'&&(p.status==='publish_approved'||p.status==='master_approved')&&<HtmlVariants p={p}/>}</div>
}
export default function PublishClient(){
  const[data,setData]=useState<any[]>([]),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState('');
  const id=typeof window!=='undefined'?new URLSearchParams(location.search).get('id'):null;
  const load=async()=>{const x=await(await fetch(`/api/publish${id?`?id=${encodeURIComponent(id)}`:''}`,{cache:'no-store'})).json();setData(x.items||[])};
  useEffect(()=>{load()},[]);const item=data[0];const byPlatform=useMemo(()=>new Map((item?.packages||[]).map((p:any)=>[p.platform,p])),[item]);
  const generate=async(platform:string)=>{if(!item)return;setBusy(platform);setMsg(`K2.6 正在基于当前 Final 生成${meta[platform]?.name||platform}文案与视觉方向…`);const x=await(await fetch('/api/publish/package',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:item.content_id,platforms:[platform]})})).json();setMsg(x.ok?'方案已生成。先检查文案和视觉方向，再批准。':`生成失败：${x.error||x.errors?.join('；')}`);setBusy(null);await load()};
  if(!item)return <div className="card"><h2>还没有可制作的 Final</h2><p className="muted">先在编辑页保存 Final。</p></div>;
  const lead=String(item.final_text||'').trim().split(/\n|。|！|？/)[0].slice(0,70);
  return <><div className="card" style={{marginBottom:16}}><div className="meta"><span className="pill">Final 已确认</span><span className="pill">文案 K2.6 Thinking</span><span className="pill">HTML Codex</span><span className="pill">AI 生图暂缓</span></div><h1 style={{fontSize:28,marginTop:10}}>公众号视觉母版</h1><h2 style={{marginTop:12}}>{lead}{lead.length>=70?'…':''}</h2><p className="muted">当前只做一件事：把人工 Final 制作为公众号视觉母版。HTML、图片和封面确认后，进入发布页，再由 Codex 按同一视觉系统重新排版小红书和抖音图文。</p><details><summary className="muted" style={{cursor:'pointer'}}>查看当前 Final</summary><div style={{whiteSpace:'pre-wrap',lineHeight:1.8,marginTop:12}}>{item.final_text}</div></details></div><ArchiveCard item={item} onChanged={load}/>{msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}<div className="grid">{order.map(platform=>{const p:any=byPlatform.get(platform);return <div className="card span-12" key={platform}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap'}}><div><h2>{meta[platform].name}</h2><p className="muted">{meta[platform].desc}</p></div><button disabled={!!busy} onClick={()=>generate(platform)}>{busy===platform?'生成中…':p?'重新生成方案':'开始制作'}</button></div>{p?<PackageEditor p={p} onChanged={load}/>:<div className="muted" style={{padding:'22px 0'}}>还没有生成这一平台方案。</div>}</div>})}</div></>
}
