'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';

function TopicCard({t,saved,onSave,onSelect,selecting}:{t:any;saved:boolean;onSave:(id:string,v:boolean)=>Promise<void>;onSelect:(id:string)=>Promise<void>;selecting:boolean}){
  return <div className="card span-6 topic">
    <div className="meta"><span className="pill">{t.column==='yueli'?'乐里':'乐室'}</span><span className="pill">综合 {t.score??'—'}</span><span className="pill">音乐匹配 {t.voxFit}</span><span className="pill">互动热度 {t.audible}</span><span className="pill">时效 {t.freshness}</span>{saved&&<span className="pill">已保存</span>}</div>
    <h2>{t.title}</h2><div><strong>为什么现在：</strong>{t.whyNow}</div><div><strong>VOX 角度：</strong>{t.voxAngle}</div><div className="muted" style={{wordBreak:'break-all'}}>来源：{t.source}</div><div className="muted">方向：{t.format}</div>
    <div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}><button disabled={selecting} onClick={()=>onSelect(t.id)}>{selecting?'正在创建内容…':'开始写作'}</button><button className="secondary" disabled={selecting} onClick={()=>onSave(t.id,!saved)}>{saved?'取消保存':'保存选题'}</button>{t.sourceUrl&&<a className="button-link secondary" href={t.sourceUrl} target="_blank" rel="noreferrer" title="将在新标签打开外部来源；可能需要登录、验证码或受地区限制">查看外部原文 ↗</a>}</div>
  </div>
}

export default function TopicsClient(){
  const refreshAbort=useRef<AbortController|null>(null);
  const[items,setItems]=useState<any[]>([]),[saved,setSaved]=useState<any[]>([]),[busy,setBusy]=useState(false),[selecting,setSelecting]=useState(''),[msg,setMsg]=useState('');
  const[manualTitle,setManualTitle]=useState(''),[manualNotes,setManualNotes]=useState(''),[manualBusy,setManualBusy]=useState(false),[manualError,setManualError]=useState('');
  const load=async()=>{const x=await (await fetch('/api/topics',{cache:'no-store'})).json();setItems(x.items||[]);setSaved(x.saved||[])};
  useEffect(()=>{load()},[]);
  const refresh=async()=>{setBusy(true);const controller=new AbortController();refreshAbort.current=controller;const started=Date.now();const stages=['正在收集来源…','正在筛选可用信息…','正在排序选题…'];let stage=0;setMsg(stages[0]);const ticker=window.setInterval(()=>{stage=Math.min(stage+1,stages.length-1);setMsg(`${stages[stage]} 已等待 ${Math.round((Date.now()-started)/1000)} 秒`)},15000);const timer=window.setTimeout(()=>controller.abort(),60000);try{const r=await fetch('/api/research/run',{method:'POST',headers:{'content-type':'application/json'},body:'{}',signal:controller.signal});const x=await r.json();await load();setMsg(`已找到 ${x.fetched||0} 条新信息。下一步：选择一个想写的选题。`)}catch(e:any){setMsg(e?.name==='AbortError'?'更新超过 60 秒，已停止等待。旧选题仍然可以使用，可以稍后重试。':`更新失败：${e?.message||e}。旧选题仍然可以使用。`)}finally{window.clearInterval(ticker);window.clearTimeout(timer);refreshAbort.current=null;setBusy(false)}};
  const select=async(id:string)=>{setSelecting(id);setMsg('正在创建写作任务…');try{const r=await fetch('/api/topics/select',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topicId:id})}),x=await r.json();if(!r.ok||!x.contentId)throw Error(x.error||'创建写作任务失败，请重试');location.href=`/editor?id=${encodeURIComponent(x.contentId)}`}catch(e:any){setMsg(`创建写作任务失败：${e?.message||e}`);setSelecting('')}};
  const createManual=async(e:FormEvent)=>{e.preventDefault();if(manualBusy)return;setManualError('');const title=manualTitle.trim();if([...title].length<2){setManualError('请先写下一句你想讨论的话题。');return}setManualBusy(true);try{const r=await fetch('/api/topics/manual',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,notes:manualNotes.trim()})}),x=await r.json();if(!r.ok||!x.contentId)throw Error(x.error||'创建我的选题失败，请重试');location.href=`/editor?id=${encodeURIComponent(x.contentId)}`}catch(error:any){setManualError(error?.message||'创建我的选题失败，请重试。');setManualBusy(false)}};
  const saveTopic=async(id:string,v:boolean)=>{const x=await (await fetch('/api/topics/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topicId:id,saved:v})})).json();if(x.ok){setMsg(v?'选题已保存，后续刷新热点不会消失。':'已取消保存。');await load()}else setMsg('保存失败：'+x.error)};
  return <>
    <section className="card manual-topic-card" id="manual-topic" aria-labelledby="manual-topic-title"><div><div className="eyebrow">自己的起点</div><h2 id="manual-topic-title">写下我的话题</h2><p className="muted">不必等推荐。一个问题、一句困扰或还没想清楚的念头就够了；下一步可以和 Sinote 一起聊清楚。</p></div><form className="manual-topic-form" onSubmit={createManual}><label htmlFor="manual-topic-title-input">我想写什么？</label><input id="manual-topic-title-input" className="text-input" value={manualTitle} onChange={e=>setManualTitle(e.target.value)} maxLength={140} placeholder="例如：我想写为什么练琴总是拖延" autoComplete="off"/><label htmlFor="manual-topic-notes">补充说明 <span className="muted">（可选）</span></label><textarea id="manual-topic-notes" className="manual-topic-notes" value={manualNotes} onChange={e=>setManualNotes(e.target.value)} maxLength={3000} placeholder="为什么此刻想写？想到的经历、例子或一句原话都可以。"/><div className="creator-actions"><button type="submit" disabled={manualBusy||[...manualTitle.trim()].length<2}>{manualBusy?'正在开始…':'自己开始写 →'}</button></div>{manualError&&<p className="manual-topic-error" role="alert">{manualError}</p>}</form></section>
    <div style={{display:'flex',gap:10,alignItems:'center',marginBottom:16,flexWrap:'wrap'}}><button onClick={refresh} disabled={busy}>{busy?'更新中…':'刷新今日灵感'}</button><span className="muted">音乐、音乐行业、乐队和摇滚历史优先；会综合参考互动、匹配度和时效。外部原文会在新标签打开；即使外站受限，Sinote 中的来源与选题依据仍保留。</span></div>
    {msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}
    {saved.length>0&&<section style={{marginBottom:28}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:12}}><div><h2 style={{fontSize:22,marginBottom:4}}>已保存选题</h2><div className="muted">{saved.length} 个 · 不受热点刷新影响</div></div></div><div className="grid">{saved.map(t=><TopicCard key={t.id} t={t} saved onSave={saveTopic} onSelect={select} selecting={selecting===t.id}/>)}</div></section>}
    <section><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:12}}><div><h2 style={{fontSize:22,marginBottom:4}}>今日候选 Top 20</h2><div className="muted">优先看有真实点赞、评论、回复、分享、浏览/播放信号的音乐选题。</div></div></div><div className="grid">{items.slice(0,20).map(t=><TopicCard key={t.id} t={t} saved={false} onSave={saveTopic} onSelect={select} selecting={selecting===t.id}/>)}</div>{items.length===0&&<div className="card muted">当前没有未保存候选，点“刷新真实热点”获取新选题。</div>}</section>
  </>;
}
