'use client';
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';
function TopicCard({t,saved,onSave,onSelect,selecting}:{t:any;saved:boolean;onSave:(id:string,v:boolean)=>void;onSelect:(id:string)=>void;selecting:boolean}){return <article className="card topic-card"><div className="meta"><span className="pill">{t.category||'推荐'}</span>{t.score!=null&&<span className="pill">推荐度 {t.score}</span>}</div><h2>{t.title}</h2>{t.summary&&<p>{t.summary}</p>}{t.why&&<p className="muted">判断依据：{t.why}</p>}{t.sourceSummary&&<p className="muted">来源摘要：{t.sourceSummary}</p>}<div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}><button disabled={selecting} onClick={()=>onSelect(t.id)}>{selecting?'正在创建内容…':'开始写作'}</button><button className="secondary" disabled={selecting} onClick={()=>onSave(t.id,!saved)}>{saved?'取消保存':'保存选题'}</button>{t.sourceUrl&&<a className="button-link secondary" href={t.sourceUrl} target="_blank" rel="noreferrer" title="将在新标签打开外部来源，可能需要登录或受地区限制">查看外部原文 ↗</a>}</div></article>}
export default function TopicsClient({initialItems=[],initialSaved=[]}:{initialItems?:any[];initialSaved?:string[]}){
  const refreshAbort=useRef<AbortController|null>(null);
  const[items,setItems]=useState<any[]>(initialItems),[saved,setSaved]=useState<string[]>(initialSaved),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[selecting,setSelecting]=useState(''),[manualTitle,setManualTitle]=useState(''),[manualNotes,setManualNotes]=useState(''),[manualBusy,setManualBusy]=useState(false),[manualError,setManualError]=useState('');
  const savedSet=useMemo(()=>new Set(saved),[saved]);
  const load=async()=>{const x=await (await fetch('/api/topics',{cache:'no-store'})).json();setItems(x.items||[]);setSaved(x.saved||[])};
  useEffect(()=>{if(!initialItems.length)load()},[]);
  const refresh=async()=>{setBusy(true);const controller=new AbortController();refreshAbort.current=controller;const started=Date.now();const stages=['正在收集来源…','正在筛选可用信息…','正在排序选题…'];let stage=0;setMsg(stages[0]);const ticker=window.setInterval(()=>{stage=Math.min(stage+1,stages.length-1);setMsg(`${stages[stage]} 已等待 ${Math.round((Date.now()-started)/1000)} 秒`)},15000);const timer=window.setTimeout(()=>controller.abort(),60000);try{const r=await fetch('/api/research/run',{method:'POST',headers:{'content-type':'application/json'},body:'{}',signal:controller.signal});const x=await r.json();await load();setMsg(`热点已更新，找到 ${x.fetched||0} 条新信息。下一步：选择一个最想写的选题。`)}catch(e:any){setMsg(e?.name==='AbortError'?'更新超过 60 秒，已停止等待。旧选题仍然可以使用，可以稍后重试。':`更新失败：${e?.message||e}。旧选题仍然可以使用。`)}finally{window.clearInterval(ticker);window.clearTimeout(timer);refreshAbort.current=null;setBusy(false)}};
  const select=async(id:string)=>{setSelecting(id);setMsg('正在创建内容…');try{const r=await fetch('/api/topics/select',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topicId:id})}),x=await r.json();if(!r.ok||!x.contentId)throw Error(x.error||'创建写作内容失败，请重试');location.href=`/editor?id=${encodeURIComponent(x.contentId)}`}catch(e:any){setMsg(`创建写作内容失败：${e?.message||e}`);setSelecting('')}};
  const createManual=async(e:FormEvent)=>{e.preventDefault();if(manualBusy)return;setManualError('');const title=manualTitle.trim();if([...title].length<2){setManualError('请先写下一句你想讨论的话题。');return}setManualBusy(true);try{const r=await fetch('/api/topics/manual',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,notes:manualNotes.trim()})}),x=await r.json();if(!r.ok||!x.contentId)throw Error(x.error||'创建我的选题失败，请重试');location.href=`/editor?id=${encodeURIComponent(x.contentId)}`}catch(error:any){setManualError(error?.message||'创建我的选题失败，请重试。');setManualBusy(false)}};
  const saveTopic=async(id:string,v:boolean)=>{const x=await (await fetch('/api/topics/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topicId:id,saved:v})})).json();if(x.ok){setMsg(v?'选题已保存，后续刷新热点不会消失。':'已取消保存。');await load()}else setMsg('保存失败：'+x.error)};
  return <><div className="card" style={{marginBottom:16}}><div className="eyebrow">选题</div><h1>今天想写什么？</h1><p className="muted">可以刷新热点，也可以直接写自己的话题。外部来源会在新标签打开；即使外站需要登录或打不开，Sinote 里的来源摘要与判断依据仍会保留。</p><button onClick={refresh} disabled={busy}>{busy?'更新中…':'更新热点'}</button>{msg&&<p className="muted" style={{whiteSpace:'pre-wrap'}}>{msg}</p>}</div><form id="manual-topic" className="card" onSubmit={createManual} style={{marginBottom:16}}><h2>我已经有想法</h2><input className="text-input" value={manualTitle} onChange={e=>setManualTitle(e.target.value)} placeholder="一句话写下你想讨论的内容"/><textarea value={manualNotes} onChange={e=>setManualNotes(e.target.value)} placeholder="可选：补充背景、经历或资料"/><button disabled={manualBusy||!manualTitle.trim()}>{manualBusy?'正在创建…':'开始写作'}</button>{manualError&&<p className="muted">{manualError}</p>}</form><div className="grid">{items.map(t=><TopicCard key={t.id} t={t} saved={savedSet.has(t.id)} onSave={saveTopic} onSelect={select} selecting={selecting===t.id}/>)}</div></>
}
