import fs from 'node:fs';
import path from 'node:path';
import {execFile,spawn} from 'node:child_process';
import {promisify} from 'node:util';
import {beginCoverGeneration,completeCoverGeneration,ensureCoverSpec,failCoverGeneration,getPublishPackage,recoverStaleCoverGeneration} from '../../../../lib/db';
import {runCodex} from '../html/route';
export const runtime='nodejs';export const maxDuration=900;
const execFileAsync=promisify(execFile);const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';async function verifyCoverHtmlImages(url:string){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('COVER_HTML_NOT_LOADABLE');const h=await r.text();for(const m of h.matchAll(/<img\b[^>]*\bsrc=[\"']([^\"']+)[\"']/gi)){const src=m[1].replace(/&amp;/g,'&'),u=new URL(src,url).toString(),ir=await fetch(u,{cache:'no-store'});if(!ir.ok||!String(ir.headers.get('content-type')||'').startsWith('image/'))throw Error('COVER_RENDERED_IMAGE_NOT_LOADABLE: '+src)}}
function stableChromeScreenshot(url:string,out:string,width:number,height:number,budget=2200){try{fs.unlinkSync(out)}catch{}return new Promise<void>((resolve,reject)=>{const p=spawn(chrome,['--headless=new','--hide-scrollbars','--disable-gpu','--force-device-scale-factor=1',`--window-size=${width},${height}`,`--virtual-time-budget=${budget}`,`--screenshot=${out}`,url],{stdio:'ignore'});let done=false,last=-1,stable=0,timeout:any;const finish=(err?:Error)=>{if(done)return;done=true;clearInterval(timer);if(timeout)clearTimeout(timeout);try{p.kill('SIGTERM')}catch{};err?reject(err):resolve()};const timer=setInterval(()=>{try{const n=fs.statSync(out).size;if(n>20000&&n===last)stable++;else stable=0;last=n;if(stable>=2)finish()}catch{}},250);timeout=setTimeout(()=>finish(new Error('COVER_SCREENSHOT_TIMEOUT')),45000);p.on('error',e=>{clearTimeout(timeout);finish(e)});p.on('close',()=>{clearTimeout(timeout);try{if(fs.statSync(out).size>20000)return finish()}catch{};finish(new Error('COVER_SCREENSHOT_PROCESS_EXITED'))})})}
function rel(abs:string){return path.relative(process.cwd(),abs).split(path.sep).join('/')}
function queueWorker(id:string,generationId:string){const port=process.env.PORT||'3000',body=JSON.stringify({id,generationId,worker:true});const p=spawn('/usr/bin/curl',['-sS','-X','POST',`http://127.0.0.1:${port}/api/publish/render`,'-H','content-type: application/json','--data-binary',body],{detached:true,stdio:'ignore'});p.on('error',e=>{try{failCoverGeneration(id,String(e?.message||e),generationId)}catch{}});p.unref();}
export async function POST(req:Request){let id='',generationId='';try{const x=await req.json();id=String(x.id||'');if(!id)return Response.json({ok:false,error:'id required'},{status:400});const pkg:any=getPublishPackage(id);if(!pkg)return Response.json({ok:false,error:'package not found'},{status:404});if(pkg.platform!=='wechat_long_image')return Response.json({ok:false,error:'GC cover is enabled for WeChat package only'},{status:409});if(!fs.existsSync(chrome))throw new Error('CHROME_NOT_FOUND');
if(!x.worker){const current=recoverStaleCoverGeneration(id);if(current.status==='generating')return Response.json({ok:true,queued:true,alreadyRunning:true,cover:current},{status:202});const cover=beginCoverGeneration(id);generationId=String(cover.generation_id||'');queueWorker(id,generationId);return Response.json({ok:true,queued:true,generationId,cover},{status:202});}
generationId=String(x.generationId||'');const current=ensureCoverSpec(id);if(!generationId||current.status!=='generating'||current.generation_id!==generationId)return Response.json({ok:false,error:'封面生成任务不存在、已结束或已超时，请重试'},{status:409});const dir=path.join(process.cwd(),'public','generated',id,'cover');fs.mkdirSync(dir,{recursive:true});const visual=path.join(dir,'gc-visual.png'),html=path.join(dir,'cover.html'),png=path.join(dir,'cover.png'),promptFile=path.join(dir,'gc-prompt.txt');for(const f of [visual,html,png,promptFile])try{fs.unlinkSync(f)}catch{}
const imageTask=`Create ONLY the GC cover artwork for one VOX WeChat article, then stop.\n\nARTICLE TITLE: ${pkg.title}\nARTICLE CONTEXT:\n${pkg.body}\n\nPACKAGE VISUAL DIRECTION:\n${pkg.visual_prompt||''}\n\nREAD:\n/Users/voxrockschool/Projects/VOX-Visual-System/vendor/gc-minimal-zine-poster-v0-1/SKILL.md\n\nTASK:\n1. Compile the GC Standard Mode image prompt and write it to ${promptFile}.\n2. Follow gc-minimal-zine-poster-v0-1 Standard Mode as the AUTHORITATIVE artwork specification. Use Codex built-in $imagegen to generate ONE vertical 3:5 Minimal Zine Poster artwork. Do not reinterpret the Skill as a horizontal banner; the horizontal WeChat format is handled later by HTML layout.\n3. Save/copy the selected artwork exactly to ${visual}. Do not put the VOX logo or reliable Chinese headline inside the generated bitmap.\n4. Verify ${visual} and ${promptFile} exist. Do not create HTML. Do not modify unrelated files.\n5. Built-in $imagegen only; do not use OPENAI_API_KEY CLI fallback.`;
await runCodex(imageTask,process.cwd());if(!fs.existsSync(visual))throw new Error('CODEX_COVER_IMAGE_MISSING');
const visualRel=rel(visual).replace(/^public\/generated\/[^/]+\//,''),visualApi=`/api/publish/generated-file?packageId=${encodeURIComponent(id)}&file=${encodeURIComponent(visualRel)}`,logoApi=`/api/publish/cover-file?packageId=${encodeURIComponent(id)}&kind=logo`;
const layoutTask=`Create ONLY the final HTML/CSS layout for an existing generated GC artwork. Do NOT call image generation.\n\nARTICLE TITLE (verbatim): ${pkg.title}\nEXISTING ARTWORK FILE: ${visual}\nOUTPUT HTML: ${html}\nBROWSER ARTWORK SRC: ${visualApi}\nBROWSER VOX LOGO SRC: ${logoApi}\n\nREAD:\n/Users/voxrockschool/Projects/VOX-Visual-System/vendor/gc-minimal-zine-poster-v0-1/SKILL.md\n/Users/voxrockschool/Projects/VOX-Visual-System/DESIGN.md\n\nRULES:\n- Standalone 2350×1000 HTML/CSS, exact size, no margin, no scrollbars.\n- The artwork was already generated by Minimal Zine Poster v0.1. Do not redraw, regenerate, crop, recolor, or alter it. Place the complete poster with object-fit:contain as the visual anchor inside the horizontal shell.\n- Add ARTICLE TITLE verbatim in a serif stack: Huiwen Mincho / 汇文明朝体 / Source Han Serif SC / Toppan Bunkyu Mincho / Hiragino Mincho ProN / Songti SC.\n- Add the existing VOX logo via BROWSER VOX LOGO SRC, preferably upper-right. Never redraw the logo.\n- Keep 55%–75% breathing room and avoid commercial-ad hierarchy. Do not invent additional cover copy beyond ARTICLE TITLE and existing logo.\n- Use exactly the BROWSER SRC URLs above for images so the dynamically generated files load in production.\n- Verify OUTPUT HTML exists. Do not modify the artwork or unrelated files.`;
await runCodex(layoutTask,process.cwd());if(!fs.existsSync(html))throw new Error('CODEX_COVER_HTML_MISSING');const layout=fs.readFileSync(html,'utf8');if(!layout.includes(visualApi))throw new Error('COVER_HTML_VISUAL_SRC_MISMATCH');if(!layout.includes(logoApi))throw new Error('COVER_HTML_LOGO_SRC_MISMATCH');for(const src of [visualApi,logoApi]){const r=await fetch('http://127.0.0.1:3000'+src,{cache:'no-store'});if(!r.ok||!String(r.headers.get('content-type')||'').startsWith('image/'))throw new Error('COVER_ASSET_NOT_LOADABLE: '+src)}
const htmlRel=rel(html).replace(/^public\/generated\/[^/]+\//,''),shotUrl=`http://127.0.0.1:3000/api/publish/generated-file?packageId=${encodeURIComponent(id)}&file=${encodeURIComponent(htmlRel)}`;await verifyCoverHtmlImages(shotUrl);await stableChromeScreenshot(shotUrl,png,2350,1000,2500);if(!fs.existsSync(png)||fs.statSync(png).size<20000)throw new Error('COVER_SCREENSHOT_INVALID');const promptText=fs.existsSync(promptFile)?fs.readFileSync(promptFile,'utf8').slice(0,12000):'';const cover=completeCoverGeneration(id,{visualPath:rel(visual),htmlPath:rel(html),pngPath:rel(png),model:'Minimal Zine Poster v0.1 · Codex built-in $imagegen / GPT Image 2',promptText},generationId);return Response.json({ok:true,cover:{...cover,pngUrl:`/api/publish/cover-file?packageId=${encodeURIComponent(id)}&kind=png`,visualUrl:`/api/publish/cover-file?packageId=${encodeURIComponent(id)}&kind=visual`,htmlUrl:`/api/publish/cover-file?packageId=${encodeURIComponent(id)}&kind=html`}})}catch(e:any){if(id)try{failCoverGeneration(id,String(e.message||e),generationId||undefined)}catch{}return Response.json({ok:false,error:String(e.message||e).slice(0,1400)},{status:500})}}
